<?php
/*
 * generated by INWX on 2025-08-11T10:21:37+02:00
 *
 */
$_LANG['inwx_RegistrantsBirthdate'] = 'Registrant\'s birthdate';
$_LANG['inwx_RegistrantsBirthplace'] = 'Registrant\'s birthplace';
$_LANG['inwx_TrademarkName'] = 'Trademark Name';
$_LANG['inwx_TrademarkNumber'] = 'Trademark Number';
$_LANG['inwx_CompanyNo'] = 'Company reg. number';
$_LANG['inwx_VatNo'] = 'VAT number';
$_LANG['inwx_IDcardNo'] = 'ID card no.';
$_LANG['inwx_IDcardIssuerDate'] = 'ID card issue date';
$_LANG['inwx_SkLegalForm'] = '.SK Legal form';
$_LANG['inwx_UsAppPurpose'] = '.US App Purpose';
$_LANG['inwx_UsNexusCategory'] = '.US Nexus category';
$_LANG['inwx_AEImportantNotice'] = '.AE Important Notice';
$_LANG['inwx_NameEmailForward'] = '.NAME Email Forwarding';
$_LANG['inwx_NicSeIdNumber'] = '.SE ID number';
$_LANG['inwx_IDcardIssuer'] = 'ID card issuer';
$_LANG['inwx_CaLegalType'] = '.CA legal type';
$_LANG['inwx_ItCodiceFiscale'] = '.IT codice fiscale';
$_LANG['inwx_FiHenkilotunnus'] = 'Henkilötunnus';
$_LANG['inwx_TaxNumber'] = 'Tax number';
$_LANG['inwx_AeroEnsAuthId'] = '.AERO ID';
$_LANG['inwx_AeroEnsAuthKey'] = '.AERO KEY';
$_LANG['inwx_DunsNumber'] = 'DUNS number';
$_LANG['inwx_EeaLocalId'] = 'Local ID within the EEA';
$_LANG['inwx_AuDomainIdType'] = '.AU identification type';
$_LANG['inwx_AuDomainRelation'] = '.AU domain relation';
$_LANG['inwx_AuDomainRelationType'] = '.AU owner type';
$_LANG['inwx_KrCtfyType'] = '.KR certify type';
$_LANG['inwx_KrCtfyNo'] = '.KR certify number';
$_LANG['inwx_AdminBirthDate'] = 'Birthdate of the administrative contact';
$_LANG['inwx_AdminIdcardOrPassportNumber'] = 'Id card number of the administrative contact';
$_LANG['inwx_TechBirthDate'] = 'Birthdate of the technical contact';
$_LANG['inwx_TechIdcardOrPassportNumber'] = 'Id card number of the technical contact';
$_LANG['inwx_OwnerContactNameIsLegalRepresentative'] = 'I confirm that the domain owner contact name is a legal representative of the company as mentioned in the business registration certificate.';
$_LANG['inwx_BgRegistrationTacApproved'] = 'I confirm to send the necessary documents by postal mail on time within 30 days after request. This is valid from receipt of documents by the recipient. After the registration request, a notification about documents available to download within the domainlist is usually given within one working day.';
$_LANG['inwx_CnIcpNumber'] = '.CN ICP number';
$_LANG['inwx_CnRegistrationTacApproved'] = 'I am aware that authentic, accurate and complete documentation must be submitted for registration. For individual persons a copy of an official document as proof of identity of the domain owner (ID card, passport, driver\'s licence etc.) is required and for companies a copy of a document as validation of the company registration (business license, business certificate etc.).
I have read and understood the registration rules and policies of the registry CNNIC. The policies governing the contents of the websites under the domain name must be respected.
In case the domain is used for a website where the webserver is located in mainland China, a valid ICP number obtained from MIIT must be presented.
I myself am responsable for the suspension of the domain or any consequences caused by violations of the commitments and I am aware that the registry and the registrar undertake no responsibility in case of the suspension of the domain.';
$_LANG['inwx_BgApplicationNumber'] = '.BG application number';
$_LANG['inwx_IrNationalId'] = 'Iranian National-ID';
$_LANG['inwx_IrOrganizationId'] = 'Iranian Organization ID';
$_LANG['inwx_IrCompanyRegistrationCenter'] = 'Company registration center';
$_LANG['inwx_IrCompanyRegistrationCc'] = 'Country of Company registration center';
$_LANG['inwx_IrCompanyRegistrationSp'] = 'State or province of the Company registration center';
$_LANG['inwx_IrCompanyRegistrationType'] = '.IR Company type';
$_LANG['inwx_BrCpf'] = 'CPF (brazilian tax number)';
$_LANG['inwx_BrCnpj'] = 'CNPJ (brazilian company number)';
$_LANG['inwx_HrOib'] = 'OIB (croatian ID)';
$_LANG['inwx_TechTaxNumber'] = 'Tax number of the technical contact';
$_LANG['inwx_TechVatNumber'] = 'VAT number of the technical contact';
$_LANG['inwx_IdcardCc'] = 'Country of ID card';
$_LANG['inwx_ES-NIF-NIE'] = 'Spanish Tax Number (NIF/NIE)';
$_LANG['inwx_ES-ADMIN-NIF-NIE'] = 'Spanish Tax Number of the Admin contact (NIF/NIE)';
$_LANG['inwx_ES-LEGAL-FORM'] = '.ES legal form of the registrant';
$_LANG['inwx_ES-ID-TYPE'] = '.ES Identification type of the registrant';
$_LANG['inwx_ES-ADMIN-ID-TYPE'] = '.ES Identification type of the administrative contact';
$_LANG['inwx_NO-PERSON-IDENTIFIER'] = '.NO Person Identifier (PID)';
$_LANG['inwx_IS-KENNITALA'] = 'Icelandic ID number (Kennitala)';
$_LANG['inwx_SG-ADMIN-SINGPASSID'] = 'Singapore Personal Access ID of the administrative contact';
$_LANG['inwx_TAX-OFFICE'] = 'Tax Office';
$_LANG['inwx_ACKNOWLEDGE-SECURE-ONLY-APP'] = 'I am aware that my new .APP domain is more secure since it is HSTS preloaded and I need to run my website with an SSL certificate in order to use the domain. I have been notified by INWX how to order an SSL certificate to use my .APP domain.';
$_LANG['inwx_ACKNOWLEDGE-SECURE-ONLY-PAGE'] = 'I am aware that my new .PAGE domain is more secure since it is HSTS preloaded and I need to run my website with an SSL certificate in order to use the domain. I have been notified by INWX how to order an SSL certificate to use my .PAGE domain.';
$_LANG['inwx_TRAVEL-IN-INDUSTRY'] = 'Registrations with .travel are meant for all people or businesses engaged in all things travel related. Registrants of .travel domains should acknowledge prior to Registration that they are engaged in or plan to engage in activities related to travel. By registering and confirming the registration, you warrant to fulfill this requirement. Proof may be required at a later date by the registry. If the proof is not provided, the domain can be suspended.';
$_LANG['inwx_ACKNOWLEDGE-SECURE-ONLY-DEV'] = 'I am aware that my new .DEV domain is more secure since it is HSTS preloaded and I need to run my website with an SSL certificate in order to use the domain. I have been notified by INWX how to order an SSL certificate to use my .DEV domain.';
$_LANG['inwx_LEGAL-REPRESENTATIVE'] = 'Legal Representative';
$_LANG['inwx_INTENDED-USE'] = 'Intended use';
$_LANG['inwx_ACKNOWLEDGE-SECURE-ONLY-NEW'] = 'I am aware that my new .NEW domain is more secure since it is HSTS preloaded and I need to run my website with an SSL certificate in order to use the domain.
I have been notified by INWX how to order an SSL certificate to use my .NEW domain.';
$_LANG['inwx_DOT-NEW-CONFIRMATION'] = '.NEW is exclusivly for performing new actions online. Navigating to a .NEW domain must allow the user to generate action or
create online content with at most one click. No other use cases are allowed. By registering a .NEW domain, you agree to follow
the .NEW Registration Policy, including ensuring that your domain will be live and compliant within 100 days of the registration date.
Registrations that do not comply with the Registration Policy may be locked or deleted without refund. Please visit https://www.registry.google/policies/registration/new/#!/ for the full policy.';
$_LANG['inwx_GAY-ACCEPT-REQUIREMENTS'] = 'I accept the .gay Rights Protections Policy at <a href=\'https://toplevel.design/policy\' target=\'_blank\'>https://toplevel.design/policy</a><br>
20% of the revenues from new .gay domain registrations are donated to non-profit LGBTQ organisations.';
$_LANG['inwx_COOP-ACCEPT-REQUIREMENTS'] = 'I, the registrant, understand, agree to, and certify that my organization meets at least one of the .COOP eligibility requirements:

* a democratically controlled member-owned cooperative, consistent with the International 7 Cooperative Principles or
* an Association comprised of cooperatives or
* an Organization that is majority controlled by a Cooperative or
* an Entity whose operations are principally dedicated to serving Cooperatives.
I understand and agree that DotCooperation LLC conducts audits of .COOP domain registrations and reserves the right to cancel or modify a domain name in accordance with their policies.';
$_LANG['inwx_NGO-ACCEPT-REQUIREMENTS'] = 'I, the registrant, understand and agree to the <a href=\'https://pir.org/our-impact/ngo-ong-policy/\' target=\'_blank\'>.ngo & .ong Registration Policies</a> and certify that my organization meets the eligibility requirements therein.';
$_LANG['inwx_ACKNOWLEDGE-SECURE-ONLY-DAY'] = 'I am aware that my new .DAY domain is more secure since it is HSTS preloaded and I need to run my website with an SSL certificate in order to use the domain. I have been notified by INWX how to order an SSL certificate to use my .DAY domain.';
$_LANG['inwx_ACKNOWLEDGE-SECURE-ONLY-BOO'] = 'I am aware that my new .BOO domain is more secure since it is HSTS preloaded and I need to run my website with an SSL certificate in order to use the domain. I have been notified by INWX how to order an SSL certificate to use my .BOO domain.';
$_LANG['inwx_ACKNOWLEDGE-SECURE-ONLY-RSVP'] = 'I am aware that my new .RSVP domain is more secure since it is HSTS preloaded and I need to run my website with an SSL certificate in order to use the domain. I have been notified by INWX how to order an SSL certificate to use my .DAY domain.';
$_LANG['inwx_DK-ACCEPT-REGISTRAR'] = '<b>Accept registrar management for your domain</b><br/><br/>
I accept that INWX manages my .dk domain name. You agree that you give INWX the rights to make payments to DK Hostmaster, change nameservers, contact informations or cancelling the domain name on your behalf.
You can change this at Dk Hostmaster\'s self-service anytime. You can find more information <a href=\"https://www.dk-hostmaster.dk/en/who-dk-hostmaster\" target=\"_blank\">here</a>';
$_LANG['inwx_ACKNOWLEDGE-SECURE-ONLY-MOV'] = 'I am aware that my new .MOV domain is more secure since it is HSTS preloaded and I need to run my website with an SSL certificate in order to use the domain. I have been notified by INWX how to order an SSL certificate to use my .MOV domain.';
$_LANG['inwx_ACKNOWLEDGE-SECURE-ONLY-PHD'] = 'I am aware that my new .PHD domain is more secure since it is HSTS preloaded and I need to run my website with an SSL certificate in order to use the domain. I have been notified by INWX how to order an SSL certificate to use my .PHD domain.';
$_LANG['inwx_ACKNOWLEDGE-SECURE-ONLY-PROF'] = 'I am aware that my new .PROF domain is more secure since it is HSTS preloaded and I need to run my website with an SSL certificate in order to use the domain. I have been notified by INWX how to order an SSL certificate to use my .PROF domain.';
$_LANG['inwx_ACKNOWLEDGE-SECURE-ONLY-ESQ'] = 'I am aware that my new .ESQ domain is more secure since it is HSTS preloaded and I need to run my website with an SSL certificate in order to use the domain. I have been notified by INWX how to order an SSL certificate to use my .ESQ domain.';
$_LANG['inwx_ACKNOWLEDGE-SECURE-ONLY-NEXUS'] = 'I am aware that my new .NEXUS domain is more secure since it is HSTS preloaded and I need to run my website with an SSL certificate in order to use the domain. I have been notified by INWX how to order an SSL certificate to use my .NEXUS domain.';
$_LANG['inwx_ACKNOWLEDGE-SECURE-ONLY-DAD'] = 'I am aware that my new .DAD domain is more secure since it is HSTS preloaded and I need to run my website with an SSL certificate in order to use the domain. I have been notified by INWX how to order an SSL certificate to use my .DAD domain.';
$_LANG['inwx_ACKNOWLEDGE-SECURE-ONLY-FOO'] = 'I am aware that my new .FOO domain is more secure since it is HSTS preloaded and I need to run my website with an SSL certificate in order to use the domain. I have been notified by INWX how to order an SSL certificate to use my .FOO domain.';
$_LANG['inwx_ACKNOWLEDGE-SECURE-ONLY-ZIP'] = 'I am aware that my new .ZIP domain is more secure since it is HSTS preloaded and I need to run my website with an SSL certificate in order to use the domain. I have been notified by INWX how to order an SSL certificate to use my .ZIP domain.';
$_LANG['inwx_HK-INDUSTRY-TYPE'] = 'Industry sector';
$_LANG['inwx_ACKNOWLEDGE-SECURE-ONLY-MEME'] = 'I am aware that my new .MEME domain is more secure since it is HSTS preloaded and I need to run my website with an SSL certificate in order to use the domain. I have been notified by INWX how to order an SSL certificate to use my .MEME domain.';
$_LANG['inwx_ACKNOWLEDGE-SECURE-ONLY-ING'] = 'I am aware that my new .ING domain is more secure since it is HSTS preloaded and I need to run my website with an SSL certificate in order to use the domain. I have been notified by INWX how to order an SSL certificate to use my .ING domain.';
$_LANG['inwx_MUSIC-ACCEPT-REQUIREMENTS'] = '<strong>.MUSIC Domain Registration Requirements</strong>
<ul>
<li><strong>Identity Verification (KYC/KYB):</strong> You must complete a mandatory identity verification process (Know Your Customer/Know Your Business) after registration. Your domain will remain inactive until this process is successfully completed. This must be done at: id.music</li>
<li><strong>Music Community Connection (Nexus Requirement):</strong> You <strong>must have a verifiable connection to the specific domain name (string)</strong> you are registering. This connection can be historical, commercial, or professional, and <strong>you cannot register any .MUSIC domain without demonstrating a legitimate link to the name</strong>. The registry will audit your claim, and failure to provide proof of this connection may result in the suspension or loss of your domain without a refund.</li>
</ul>
<strong>By proceeding with the purchase, you acknowledge and agree to these requirements.</strong>';
$_LANG['inwx_GM-ACCEPT-REQUIREMENTS'] = 'I\'ve read and understood the .GM Rules and Guidelines, including: 

An entity (person, organisation or company) residing in, providing information or services for or about The Gambia, or otherwise benefiting the local Internet community of The Gambia may register domain names through a registrar.

An organisation needing to protect their name may register a term if it is clearly and unambiguously identifying the registrant organisation. The validity of the connection is checked by the .GM ccTLD registry. When in doubt the given administrative contact / domain owner will be consulted to ascertain the connection between the applicant and the domain name.';
$_LANG['inwx_BANK-ACCEPT-REQUIREMENTS'] = 'To register a .bank domain, you must first verify your domain on the official website of the registry. When requesting this token, select \"INWX\" as the registrar in the dropdown menu. You can obtain the token from: https://register.bank/get-started/

I understand that .bank domains have special technical requirements to function properly, including: They must use DNSSEC, the DNS servers must be from the domain itself or another .BANK domain, they will only work with SSL (HSTS), I must use secure email protocols like DMARC and SPF, and my account must have two-factor authentication (2FA) active at all times.';
$_LANG['inwx_INSURANCE-ACCEPT-REQUIREMENTS'] = 'To register a .insurance domain, you must first verify your domain on the official website of the registry. When requesting this token, select \"INWX\" as the registrar in the dropdown menu. You can obtain the token from: https://www.register.insurance/get-started/

I understand that .insurance domains have special technical requirements to function properly, including: They must use DNSSEC, the DNS servers must be from the domain itself or another .INSURANCE domain, they will only work with SSL (HSTS), I must use secure email protocols like DMARC and SPF, and my account must have two-factor authentication (2FA) active at all times.';
$_LANG['inwx_CA-ACCEPT-REGISTRANT-AGREEMENT'] = 'The registrant has read and accepts the <a href=\"https://www.cira.ca/en/resources/documents/about/registrant-agreement/\" target=\"_blank\">CIRA Registrant Agreement</a>. Confirmation here in the order process is optional - alternatively, the domain holder will receive an e-mail asking them to agree to the Registrant Agreement.';
$_LANG['inwx_DK-ACCEPT-TAC'] = '<b>Yes, I accept the user agreement with Punktum dk A/S:</b><br/>
.dk Domain Name Terms and Conditions
<br/><br/>
To register a .dk domain name, you must enter into an agreement with Punktum dk A/S. Punktum dk A/S is the administrator for all .dk domain names.
<br/><br/>
Domain administrator:<br/>
Punktum dk A/S<br/>
Ørestads Boulevard 108, 11.<br/>
DK-2300 KBH S
<br/><br/>
I hereby agree to enter into an agreement on the right to use the specified .dk domain name according to the applicable terms. Among other things, this means that I will ensure my contact details as a registrant are accurate at all times. I will perform Punktum dk A/S\' identity check when requested to do so.
<br/><br/>
My right to use the specified .dk domain name may be transferred, suspended, deleted, or blocked under the conditions set out in Punktum dk A/S\' terms of use.
<br/><br/>
Pursuant to Section 18 (2) (13) of the Danish Consumer Contract Act, I agree to waive the right to withdraw from the agreement on the right to use the specified .dk domain name.
<br/><br/>
I give my consent for Punktum dk A/S, as the domain administrator, to use my personal data under its personal data policy.
<br/><br/>
I agree to pay the registrar selected by me the fee for the first registration period for the specified .dk domain name.
<br/><br/>
Links:
<br/><br/>
<a href=\"https://www.punktum.dk/en/articles/terms-and-conditions-for-the-right-of-use-to-a-dk-domain-name\" target=\"_blank\">Terms and Conditions for the Right of Use to a .dk Domain Name</a><br/>
<a href=\"https://www.punktum.dk/en/articles/privacy-policy\" target=\"_blank\">Privacy Policy</a>';
$_LANG['inwx_ACKNOWLEDGE-SECURE-ONLY-CHANNEL'] = 'I am aware that my new .CHANNEL domain is more secure since it is HSTS preloaded and I need to run my website with an SSL certificate in order to use the domain. I have been notified by INWX how to order an SSL certificate to use my .CHANNEL domain.';
$_LANG['inwx_CHANNEL-ACCEPT-REQUIREMENTS'] = '.channel is exclusively for content creators and publishers to monetize their content. All .channel domains must present the user with a website where the creator can monetize their content or audience. No other use cases are permitted. By registering a .channel domain, you agree to follow the .channel Registration Policy. Please visit g.co/registry/channelRegistration for the full policy.';
$_LANG['inwx_ES-ID'] = 'Registrant ID (NIF/NIE/VAT/ID/Passport)';
$_LANG['inwx_ES-ADMIN-ID'] = 'Admin ID (NIF/NIE/ID/Passport)';
$_LANG['inwx_ES-TECH-ID'] = 'Tech ID (NIF/NIE/ID/Passport)';
$_LANG['inwx_ES-BILLING-ID'] = 'Billing ID (NIF/NIE/ID/Passport)';
$_LANG['inwx_es_contacts'] = '<strong>IMPORTANT INFORMATION</strong>
<ul>
<li><strong>REGISTRANT</strong>: The REGISTRANT contact can be either a private person or a company.</li>
<li><strong>ADMIN CONTACT</strong>: The ADMIN contact MUST be a private person, it cannot be a company.</li>
</ul>';
