<?php
/*
 * generated by INWX on 2025-08-11T10:21:37+02:00
 *
 */
$_LANG['inwx_RegistrantsBirthdate'] = 'Fecha de nacimiento del titular';
$_LANG['inwx_RegistrantsBirthplace'] = 'Lugar de nacimiento del solicitante';
$_LANG['inwx_TrademarkName'] = 'Nombre de la marca registrada';
$_LANG['inwx_TrademarkNumber'] = 'Número de la marca registrada';
$_LANG['inwx_CompanyNo'] = 'Número de registro de la compañía';
$_LANG['inwx_VatNo'] = 'Número VAT';
$_LANG['inwx_IDcardNo'] = 'DNI/Pasaporte';
$_LANG['inwx_IDcardIssuerDate'] = 'Fecha de emisión del DNI';
$_LANG['inwx_SkLegalForm'] = 'Formulario legal .SK';
$_LANG['inwx_UsAppPurpose'] = 'Uso del dominio .US';
$_LANG['inwx_UsNexusCategory'] = 'Categoría de nexo .US';
$_LANG['inwx_AEImportantNotice'] = 'Aviso Importante de .AE';
$_LANG['inwx_NameEmailForward'] = 'Reenvio de correo electrónico en .NAME ';
$_LANG['inwx_NicSeIdNumber'] = 'Número de identificación .SE';
$_LANG['inwx_IDcardIssuer'] = 'Entidad emisora del DNI';
$_LANG['inwx_CaLegalType'] = 'Tipo de propietario para dominios .CA';
$_LANG['inwx_ItCodiceFiscale'] = 'Código fiscal para dominios .IT';
$_LANG['inwx_FiHenkilotunnus'] = 'Henkilötunnus';
$_LANG['inwx_TaxNumber'] = 'CIF o NIF';
$_LANG['inwx_AeroEnsAuthId'] = 'Identificador para dominios .AERO';
$_LANG['inwx_AeroEnsAuthKey'] = 'Llave para dominios .AERO';
$_LANG['inwx_DunsNumber'] = 'Número DUNS';
$_LANG['inwx_EeaLocalId'] = 'Identificador local dentro del EEE';
$_LANG['inwx_AuDomainIdType'] = 'Tipo de identificación para dominios .AU';
$_LANG['inwx_AuDomainRelationType'] = 'Tipo de propietario para dominios .AU';
$_LANG['inwx_AuDomainRelation'] = 'Relación de dominio para dominios .AU';
$_LANG['inwx_KrCtfyNo'] = 'Número certificado para dominios .KR';
$_LANG['inwx_KrCtfyType'] = 'Tipo de certificacion para dominios .KR';
$_LANG['inwx_AdminBirthDate'] = 'Fecha de nacimiento del contacto administrativo';
$_LANG['inwx_AdminIdcardOrPassportNumber'] = 'DNI del contacto administrativo';
$_LANG['inwx_TechBirthDate'] = 'Fecha de nacimiento del contacto técnico';
$_LANG['inwx_TechIdcardOrPassportNumber'] = 'DNI del contacto técnico';
$_LANG['inwx_OwnerContactNameIsLegalRepresentative'] = 'Confirmo que el nombre del contacto del dominio es el representante legal de la empresa tal y como se menciona en el certificado de registro de empresas.';
$_LANG['inwx_BgRegistrationTacApproved'] = 'Confirmo el envío de los documentos necesarios por correo postal dentro de los 30 días posteriores a la solicitud. Esto es válido a partir de la recepción de documentos por parte del destinatario. Después de la solicitud de registro, se notificará durante el primer día hábil que los documentos están disponibles para su descarga dentro de la lista de dominios.';
$_LANG['inwx_CnIcpNumber'] = 'Número ICP para dominios .CN';
$_LANG['inwx_CnRegistrationTacApproved'] = 'Con la presente acepto que la documentación presentada para el registro debe ser auténtica, precisa y completa. Para las personas físicas se requiere una copia de un documento oficial como prueba de la identidad del propietario del dominio (DNI, pasaporte, carné de conducir, etc) y en el caso de empresas, una copia de un documento que acredite el registro de la empresa (licencia comercial, certificado de empresa etc).
He leído y comprendido las normas de registro y políticas del registro CNNIC. Las políticas que rigen el contenido de los sitios web bajo el nombre del dominio deben ser respetadas.
En caso de que el dominio se utilice para una web cuyo servidor se encuentre en China, presentaré un número ICP válido obtenido del MIIT.
Me hago responsable de la suspensión del dominio y de cualquier consecuencia causada por violaciónes de los compromisos y soy consciente de que el registro y el registrador no asumen ninguna responsabilidad en caso de suspensión del dominio.';
$_LANG['inwx_BgApplicationNumber'] = 'Número de solicitud para dominios .BG';
$_LANG['inwx_IrNationalId'] = 'DNI Iraní';
$_LANG['inwx_IrOrganizationId'] = 'Identificador de organización iraní';
$_LANG['inwx_IrCompanyRegistrationCenter'] = 'Centro de registro de la compañía';
$_LANG['inwx_IrCompanyRegistrationCc'] = 'País en el que se encuentra el centro de registro de la compañía';
$_LANG['inwx_IrCompanyRegistrationSp'] = 'Estado o provincia en el que se encuentra el centro de registro de la compañía';
$_LANG['inwx_IrCompanyRegistrationType'] = 'Tipo de compañía para dominios .IR';
$_LANG['inwx_BrCpf'] = 'CPF (Número de identificación fiscal brasilero)';
$_LANG['inwx_BrCnpj'] = 'CPF (Número de compañía brasilero)';
$_LANG['inwx_TechVatNumber'] = 'NIF del contacto técnico';
$_LANG['inwx_TechTaxNumber'] = 'Número de identificación fiscal del contacto técnico.';
$_LANG['inwx_HrOib'] = 'OIB (Identificador croata)';
$_LANG['inwx_IdcardCc'] = 'País del DNI';
$_LANG['inwx_ES-NIF-NIE'] = 'Número de identificación fiscal español (NIF / NIE)';
$_LANG['inwx_ES-ADMIN-NIF-NIE'] = 'Número de identificación del cto. administrativo (NIF/NIE)';
$_LANG['inwx_ES-LEGAL-FORM'] = '.ES Forma jurídica del titular';
$_LANG['inwx_ES-ID-TYPE'] = 'Tipo de identificación del titular';
$_LANG['inwx_ES-ADMIN-ID-TYPE'] = '.ES Tipo de identificación del contacto administrativo';
$_LANG['inwx_NO-PERSON-IDENTIFIER'] = '.NO Identificador de persona (PID)';
$_LANG['inwx_IS-KENNITALA'] = 'Número de identificación islandés (Kennitala)';
$_LANG['inwx_SG-ADMIN-SINGPASSID'] = 'Número de identificación personal de acceso de Singapur del contacto administrativo';
$_LANG['inwx_TAX-OFFICE'] = 'Administración Fiscal';
$_LANG['inwx_ACKNOWLEDGE-SECURE-ONLY-APP'] = 'Entiendo que los dominios .APP son más seguros, pues necesitan disponer de un certificado SSL debido a que funcionan mediante HSTS, de lo contrario el dominio no resolverá. He sido informado además por INWX sobre cómo contratar un certificado SSL para utilizar mi dominio .APP.';
$_LANG['inwx_ACKNOWLEDGE-SECURE-ONLY-PAGE'] = 'Entiendo que los dominios .PAGE son más seguros, pues necesitan disponer de un certificado SSL debido a que funcionan mediante HSTS, de lo contrario el dominio no resolverá. He sido informado además por INWX sobre cómo contratar un certificado SSL para utilizar mi dominio .PAGE.';
$_LANG['inwx_TRAVEL-IN-INDUSTRY'] = 'Registros bajo .travel están destinados para cualquier persona o negocio relacionado con el turismo. Titulares de dominios .travel deben confirmar antes del registro del dominio que están relacionados o planean estar relacionados con actividades turísticas. Al aceptar este mensaje confirma que cumple con este requisito y que puede demostrarlo en el caso de que así se lo requiriera el registro oficial de .travel, de no ser así, el dominio podría llegar a ser suspendido.';
$_LANG['inwx_LEGAL-REPRESENTATIVE'] = 'Representante Legal';
$_LANG['inwx_INTENDED-USE'] = 'Uso previsto';
$_LANG['inwx_ACKNOWLEDGE-SECURE-ONLY-DEV'] = 'Entiendo que los dominios .DEV son más seguros, pues necesitan disponer de un certificado SSL debido a que funcionan mediante HSTS, de lo contrario el dominio no resolverá. He sido informado además por INWX sobre cómo contratar un certificado SSL para utilizar mi dominio .DEV.';
$_LANG['inwx_ACKNOWLEDGE-SECURE-ONLY-NEW'] = 'Soy consciente que mi nuevo dominio .NEW es más seguro gracias a que utiliza precarga HSTS y necesito hacer uso de un certificado SSL en mi sitio web para poder hacer uso del dominio.
He sido notificado por INWX sobre como solicitar un certificado SSL para utilizar mi dominio .NEW.';
$_LANG['inwx_DOT-NEW-CONFIRMATION'] = '.NEW sirve en exclusiva para llevar a cabo nuevas acciones online. El navegar a un dominio .NEW debe permitir al usuario a generar una acción o crear contenido online prácticamente con un clic. No está permitido ningún otro tipo de uso. Al registrar un dominio .NEW, usted acepta seguir la Política de registro de .NEW, incluyendo el asegurarse de que su dominio estará publicado y cumpliendo con la normativa antes de 100 días desde la fecha de registro.
Los registros que no cumplan con esta Política de Registros pueden ser bloqueados o eliminados sin derecho a devolución. Por favor visite https://www.registry.google/policies/registration/new/#!/ para leer la política completa.';
$_LANG['inwx_GAY-ACCEPT-REQUIREMENTS'] = 'Acepto la .gay Rights Protections Policy en <a href=\'https://toplevel.design/policy\' target=\'_blank\'>https://toplevel.design/policy</a><br>
El 20% de los ingresos de los nuevos registros de dominios .gay se donan a organizaciones LGBTQ sin ánimo de lucro.';
$_LANG['inwx_COOP-ACCEPT-REQUIREMENTS'] = 'Yo, el titular, entiendo, acepto y certifico que mi organización cumple con al menos uno de los requisitos de elegibilidad de .COOP:

una Cooperativa controlada democráticamente por miembros propietarios, consistente con los 7 Principios Cooperativos Internacionales; o
una Asociación formada por Cooperativas; o
una Organización que está mayoritariamente por una Cooperativa; o
una Entidad cuyas operaciones se dedican principalmente a servir a Cooperativas.
Entiendo y estoy de acuerdo que DotCooperation LLC lleva a cabo auditorías sobre dominios .COOP registrados y se reserva el derecho a cancelar o modificar un nombre de dominio en acuerdo con sus políticas.';
$_LANG['inwx_NGO-ACCEPT-REQUIREMENTS'] = 'Yo, el registrante del dominio, entiendo y acepto <a href=\'https://pir.org/our-impact/ngo-ong-policy/\' target=\'_blank\'>las políticas de registro de .ngo y .ong</a>. Certifico además que mi organización cumple con los requisitos de eligibilidad.';
$_LANG['inwx_ACKNOWLEDGE-SECURE-ONLY-DAY'] = 'Entiendo que los dominios .DAY son más seguros, pues necesitan disponer de un certificado SSL debido a que funcionan mediante HSTS, de lo contrario el dominio no resolverá. He sido informado además por INWX sobre cómo contratar un certificado SSL para utilizar mi dominio .DAY.';
$_LANG['inwx_ACKNOWLEDGE-SECURE-ONLY-BOO'] = 'Entiendo que los dominios .BOO son más seguros, pues necesitan disponer de un certificado SSL debido a que funcionan mediante HSTS, de lo contrario el dominio no resolverá. He sido informado además por INWX sobre cómo contratar un certificado SSL para utilizar mi dominio .BOO.';
$_LANG['inwx_ACKNOWLEDGE-SECURE-ONLY-RSVP'] = 'Entiendo que los dominios .RSVP son más seguros, pues necesitan disponer de un certificado SSL debido a que funcionan mediante HSTS, de lo contrario el dominio no resolverá. He sido informado además por INWX sobre cómo contratar un certificado SSL para utilizar mi dominio .RSVP.';
$_LANG['inwx_DK-ACCEPT-REGISTRAR'] = '<b>Aceptar la gestión del dominio por parte del registrador</b><br/><br/>
Acepto que INWX gestiona mi nombre de dominio .dk. Permito por tanto a INWX a llevar a cabo pagos a DK Hostmaster, cambios de servidores de nombres, información de contactos o cancelaciones del dominio en mi nombre.
Puedes modificar esto en cualquier momento en el DK Hostmaster Self-service. Encontrarás más información <a href=\"https://www.dk-hostmaster.dk/en/who-dk-hostmaster\" target=\"_blank\">aquí</a>';
$_LANG['inwx_ACKNOWLEDGE-SECURE-ONLY-MOV'] = 'Entiendo que los dominios .MOV son más seguros, pues necesitan disponer de un certificado SSL debido a que funcionan mediante HSTS, de lo contrario el dominio no resolverá. He sido informado además por INWX sobre cómo contratar un certificado SSL para utilizar mi dominio .MOV.';
$_LANG['inwx_ACKNOWLEDGE-SECURE-ONLY-PHD'] = 'Entiendo que los dominios .PHD son más seguros, pues necesitan disponer de un certificado SSL debido a que funcionan mediante HSTS, de lo contrario el dominio no resolverá. He sido informado además por INWX sobre cómo contratar un certificado SSL para utilizar mi dominio .PHD.';
$_LANG['inwx_ACKNOWLEDGE-SECURE-ONLY-PROF'] = 'Entiendo que los dominios .PROF son más seguros, pues necesitan disponer de un certificado SSL debido a que funcionan mediante HSTS, de lo contrario el dominio no resolverá. He sido informado además por INWX sobre cómo contratar un certificado SSL para utilizar mi dominio .PROF.';
$_LANG['inwx_ACKNOWLEDGE-SECURE-ONLY-ESQ'] = 'Entiendo que los dominios .ESQ son más seguros, pues necesitan disponer de un certificado SSL debido a que funcionan mediante HSTS, de lo contrario el dominio no resolverá. He sido informado además por INWX sobre cómo contratar un certificado SSL para utilizar mi dominio .ESQ.';
$_LANG['inwx_ACKNOWLEDGE-SECURE-ONLY-NEXUS'] = 'Entiendo que los dominios .NEXUS son más seguros, pues necesitan disponer de un certificado SSL debido a que funcionan mediante HSTS, de lo contrario el dominio no resolverá. He sido informado además por INWX sobre cómo contratar un certificado SSL para utilizar mi dominio .NEXUS.';
$_LANG['inwx_ACKNOWLEDGE-SECURE-ONLY-DAD'] = 'Entiendo que los dominios .DAD son más seguros, pues necesitan disponer de un certificado SSL debido a que funcionan mediante HSTS, de lo contrario el dominio no resolverá. He sido informado además por INWX sobre cómo contratar un certificado SSL para utilizar mi dominio .DAD.';
$_LANG['inwx_ACKNOWLEDGE-SECURE-ONLY-FOO'] = 'Entiendo que los dominios .FOO son más seguros, pues necesitan disponer de un certificado SSL debido a que funcionan mediante HSTS, de lo contrario el dominio no resolverá. He sido informado además por INWX sobre cómo contratar un certificado SSL para utilizar mi dominio .FOO.';
$_LANG['inwx_ACKNOWLEDGE-SECURE-ONLY-ZIP'] = 'Entiendo que los dominios .ZIP son más seguros, pues necesitan disponer de un certificado SSL debido a que funcionan mediante HSTS, de lo contrario el dominio no resolverá. He sido informado además por INWX sobre cómo contratar un certificado SSL para utilizar mi dominio .ZIP.';
$_LANG['inwx_HK-INDUSTRY-TYPE'] = 'Industry sector';
$_LANG['inwx_ACKNOWLEDGE-SECURE-ONLY-MEME'] = 'Entiendo que los dominios .MEME son más seguros, pues necesitan disponer de un certificado SSL debido a que funcionan mediante HSTS, de lo contrario el dominio no resolverá. He sido informado además por INWX sobre cómo contratar un certificado SSL para utilizar mi dominio .MEME.';
$_LANG['inwx_ACKNOWLEDGE-SECURE-ONLY-ING'] = 'Entiendo que los dominios .ING son más seguros, pues necesitan disponer de un certificado SSL debido a que funcionan mediante HSTS, de lo contrario el dominio no resolverá. He sido informado además por INWX sobre cómo contratar un certificado SSL para utilizar mi dominio .ING.';
$_LANG['inwx_MUSIC-ACCEPT-REQUIREMENTS'] = '<strong>Requisitos de Registro del Dominio .MUSIC</strong>
<ul>
<li><strong>Verificación de Identidad (KYC/KYB):</strong> Debe completar un proceso de verificación de identidad obligatorio (Conozca a Su Cliente/Conozca a Su Empresa) después de la solicitud de registro. Su dominio permanecerá inactivo hasta que este proceso se complete con éxito. Podrá llevar a cabo esta verificación en: id.music</li>
<li><strong>Conexión con la Comunidad Musical (Requisito de Nexus):</strong> Debe <strong>tener una conexión verificable con el nombre de dominio específico (string)</strong> que está registrando. Esta conexión puede ser histórica, comercial o profesional, y <strong>no puede registrar ningún dominio .MUSIC sin demostrar un vínculo legítimo con el nombre</strong>. El registro auditará su solicitud, y si no proporciona la prueba de esta conexión, puede resultar en la suspensión o pérdida de su dominio, sin posibilidad de reembolso.</li>
</ul>
<strong>Al proceder con la compra, usted reconoce y acepta estos requisitos.</strong>';
$_LANG['inwx_GM-ACCEPT-REQUIREMENTS'] = 'I\'ve read and understood the .GM Rules and Guidelines, including: 

An entity (person, organisation or company) residing in, providing information or services for or about The Gambia, or otherwise benefiting the local Internet community of The Gambia may register domain names through a registrar.

An organisation needing to protect their name may register a term if it is clearly and unambiguously identifying the registrant organisation. The validity of the connection is checked by the .GM ccTLD registry. When in doubt the given administrative contact / domain owner will be consulted to ascertain the connection between the applicant and the domain name.';
$_LANG['inwx_BANK-ACCEPT-REQUIREMENTS'] = 'Para registrar un dominio .bank, primero debe verificar su dominio en el sitio web oficial del registro, seleccione \"INWX\" como registrador en el desplegable. Puede obtener el token desde: https://register.bank/get-started/

Entiendo que los dominios .bank disponen de requisitos técnicos especiales para que puedan funcionar, entre ellos: Deben usar DNSSEC, los servidores DNS deben ser del propio dominio o de otro dominio .BANK, solamente funcionarán con SSL (HSTS), debo utilizar protocolos seguros de correo electrónico como DMARC y SPF, y mi cuenta debe disponer de verificación en dos pasos o 2FA activo en todo momento.';
$_LANG['inwx_INSURANCE-ACCEPT-REQUIREMENTS'] = 'Para registrar un dominio .insurance, primero debe verificar su dominio en el sitio web oficial del registro, seleccione \"INWX\" como registrador en el desplegable. Puede obtener el token desde: https://www.register.insurance/get-started/

Entiendo que los dominios .insurance disponen de requisitos técnicos especiales para que puedan funcionar, entre ellos: Deben usar DNSSEC, los servidores DNS deben ser del propio dominio o de otro dominio .INSURANCE, solamente funcionarán con SSL (HSTS), debo utilizar protocolos seguros de correo electrónico como DMARC y SPF, y mi cuenta debe disponer de verificación en dos pasos o 2FA activo en todo momento.';
$_LANG['inwx_CA-ACCEPT-REGISTRANT-AGREEMENT'] = 'He leído y acepto la <a href=\"https://www.cira.ca/en/resources/documents/about/registrant-agreement/\" target=\"_blank\">CIRA Registrant Agreement</a>. La confirmación aquí en el proceso de pedido es opcional - alternativamente, el titular del dominio recibirá un correo electrónico pidiéndole que acepte el Acuerdo de Registrante.';
$_LANG['inwx_DK-ACCEPT-TAC'] = '<b>Sí, acepto el acuerdo de usuario con Punktum dk A/S:</b><br/>
Términos y condiciones del nombre de dominio .dk
<br/><br/>
Para registrar un nombre de dominio .dk, debe celebrar un acuerdo con Punktum dk A/S. Punktum dk A/S es el administrador de todos los nombres de dominio .dk.
<br/><br/>
Administrador del dominio:<br/>
Punktum dk A/S<br/>
Boulevard Ørestads 108, 11.<br/>
DK-2300 KBH S
<br/><br/>
Por la presente, acepto celebrar un acuerdo sobre el derecho a utilizar el nombre de dominio .dk especificado de acuerdo con los términos aplicables. Esto incluye, entre otras cosas, que me aseguraré de que mis datos de contacto como registrante sean precisos en todo momento. Realizaré la verificación de identidad de Punktum dk A/S cuando se me solicite.
<br/><br/>
Mi derecho a usar el nombre de dominio .dk especificado puede ser transferido, suspendido, eliminado o bloqueado según las condiciones establecidas en los términos de uso de Punktum dk A/S.
<br/><br/>
De conformidad con el artículo 18 (2) (13) de la Ley de Contratos del Consumidor de Dinamarca, acepto renunciar al derecho de retractarme del acuerdo sobre el derecho a utilizar el nombre de dominio .dk especificado.
<br/><br/>
Doy mi consentimiento para que Punktum dk A/S, como administrador del dominio, utilice mis datos personales de acuerdo con su política de privacidad.
<br/><br/>
Acepto pagar al registrador seleccionado por mí la tarifa por el primer período de registro para el nombre de dominio .dk especificado.
<br/><br/>
Enlaces:
<br/><br/>
<a href=\"https://www.punktum.dk/en/articles/terms-and-conditions-for-the-right-of-use-to-a-dk-domain-name\" target=\"_blank\">Términos y condiciones para el derecho de uso de un nombre de dominio .dk</a><br/>
<a href=\"https://www.punktum.dk/en/articles/privacy-policy\" target=\"_blank\">Política de privacidad</a>';
$_LANG['inwx_ACKNOWLEDGE-SECURE-ONLY-CHANNEL'] = 'Entiendo que los dominios .CHANNEL son más seguros, pues necesitan disponer de un certificado SSL debido a que funcionan mediante HSTS, de lo contrario el dominio no resolverá. He sido informado además por INWX sobre cómo contratar un certificado SSL para utilizar mi dominio .CHANNEL.';
$_LANG['inwx_CHANNEL-ACCEPT-REQUIREMENTS'] = '.channel es exclusivamente para que los creadores y editores de contenido moneticen su contenido. Todos los dominios .channel deben presentar al usuario un sitio web donde el creador pueda monetizar su contenido o audiencia. No se permiten otros casos de uso. Al registrar un dominio .channel, aceptas seguir la Política de registro de .channel. Visita g.co/registry/channelRegistration para conocer la política completa.';
$_LANG['inwx_ES-ID'] = 'ID del Titular (NIF/NIE/VAT/ID/Pasaporte)';
$_LANG['inwx_ES-ADMIN-ID'] = 'ID cto. Administrativo (NIF/NIE/VAT/ID/Pasaporte)';
$_LANG['inwx_ES-TECH-ID'] = 'Tech ID (NIF/NIE/ID/Passport)';
$_LANG['inwx_ES-BILLING-ID'] = 'Billing ID (NIF/NIE/ID/Passport)';
$_LANG['inwx_es_contacts'] = '<strong>INFORMACIÓN IMPORTANTE</strong>
<ul>
<li><strong>TITULAR</strong>: El contacto TITULAR puede ser una persona física o una empresa/organización.</li>
<li><strong>CONTACTO ADMINISTRATIVO</strong>: El contacto ADMINISTRATIVO DEBE ser una persona física, no puede ser una empresa.</li>
</ul>';
