<?php
/*
 * generated by InterNetworX on 2015-07-16
 *
 */

// .COM.AR
$additionaldomainfields[".com.ar"] = array();
$additionaldomainfields[".com.ar"][] = array(
		"DisplayName" => "Trustee service (extra fee could be charged)",
		"Name" => "ACCEPT-TRUSTEE-TAC",
		"InwxName" => "ACCEPT-TRUSTEE-TAC",
		"Type" => "tickbox",
		"Default" => false,
		"Required" => false,
	);

// .BA
$additionaldomainfields[".ba"] = array();
$additionaldomainfields[".ba"][] = array(
		"DisplayName" => "Trustee service (extra fee could be charged)",
		"Name" => "ACCEPT-TRUSTEE-TAC",
		"InwxName" => "ACCEPT-TRUSTEE-TAC",
		"Type" => "tickbox",
		"Default" => false,
		"Required" => false,
	);

// .BG
$additionaldomainfields[".bg"] = array();
$additionaldomainfields[".bg"][] = array(
		"DisplayName" => "Trustee service (extra fee could be charged)",
		"Name" => "ACCEPT-TRUSTEE-TAC",
		"InwxName" => "ACCEPT-TRUSTEE-TAC",
		"Type" => "tickbox",
		"Default" => false,
		"Required" => false,
	);

// .CL
$additionaldomainfields[".cl"] = array();
$additionaldomainfields[".cl"][] = array(
		"DisplayName" => "Trustee service (extra fee could be charged)",
		"Name" => "ACCEPT-TRUSTEE-TAC",
		"InwxName" => "ACCEPT-TRUSTEE-TAC",
		"Type" => "tickbox",
		"Default" => false,
		"Required" => false,
	);

// .COM.BR
$additionaldomainfields[".com.br"] = array();
$additionaldomainfields[".com.br"][] = array(
		"DisplayName" => "Trustee service (extra fee could be charged)",
		"Name" => "ACCEPT-TRUSTEE-TAC",
		"InwxName" => "ACCEPT-TRUSTEE-TAC",
		"Type" => "tickbox",
		"Default" => false,
		"Required" => false,
	);

// .COM.HK
$additionaldomainfields[".com.hk"] = array();
$additionaldomainfields[".com.hk"][] = array(
		"DisplayName" => "Trustee service (extra fee could be charged)",
		"Name" => "ACCEPT-TRUSTEE-TAC",
		"InwxName" => "ACCEPT-TRUSTEE-TAC",
		"Type" => "tickbox",
		"Default" => false,
		"Required" => false,
	);

// .CO.KR
$additionaldomainfields[".co.kr"] = array();
$additionaldomainfields[".co.kr"][] = array(
		"DisplayName" => "Trustee service (extra fee could be charged)",
		"Name" => "ACCEPT-TRUSTEE-TAC",
		"InwxName" => "ACCEPT-TRUSTEE-TAC",
		"Type" => "tickbox",
		"Default" => false,
		"Required" => false,
	);

// .DE
$additionaldomainfields[".de"] = array();
$additionaldomainfields[".de"][] = array(
		"DisplayName" => "Trustee service (extra fee could be charged)",
		"Name" => "ACCEPT-TRUSTEE-TAC",
		"InwxName" => "ACCEPT-TRUSTEE-TAC",
		"Type" => "tickbox",
		"Default" => false,
		"Required" => false,
	);

// .DZ
$additionaldomainfields[".dz"] = array();
$additionaldomainfields[".dz"][] = array(
		"DisplayName" => "Trustee service (extra fee could be charged)",
		"Name" => "ACCEPT-TRUSTEE-TAC",
		"InwxName" => "ACCEPT-TRUSTEE-TAC",
		"Type" => "tickbox",
		"Default" => false,
		"Required" => false,
	);

// .EE
$additionaldomainfields[".ee"] = array();
$additionaldomainfields[".ee"][] = array(
		"DisplayName" => "Trustee service (extra fee could be charged)",
		"Name" => "ACCEPT-TRUSTEE-TAC",
		"InwxName" => "ACCEPT-TRUSTEE-TAC",
		"Type" => "tickbox",
		"Default" => false,
		"Required" => false,
	);

// .EU
$additionaldomainfields[".eu"] = array();
$additionaldomainfields[".eu"][] = array(
		"DisplayName" => "Trustee service (extra fee could be charged)",
		"Name" => "ACCEPT-TRUSTEE-TAC",
		"InwxName" => "ACCEPT-TRUSTEE-TAC",
		"Type" => "tickbox",
		"Default" => false,
		"Required" => false,
	);

// .FI
$additionaldomainfields[".fi"] = array();
$additionaldomainfields[".fi"][] = array(
		"DisplayName" => "Trustee service (extra fee could be charged)",
		"Name" => "ACCEPT-TRUSTEE-TAC",
		"InwxName" => "ACCEPT-TRUSTEE-TAC",
		"Type" => "tickbox",
		"Default" => false,
		"Required" => false,
	);

// .FR
$additionaldomainfields[".fr"] = array();
$additionaldomainfields[".fr"][] = array(
		"DisplayName" => "Trustee service (extra fee could be charged)",
		"Name" => "ACCEPT-TRUSTEE-TAC",
		"InwxName" => "ACCEPT-TRUSTEE-TAC",
		"Type" => "tickbox",
		"Default" => false,
		"Required" => false,
	);

// .GE
$additionaldomainfields[".ge"] = array();
$additionaldomainfields[".ge"][] = array(
		"DisplayName" => "Trustee service (extra fee could be charged)",
		"Name" => "ACCEPT-TRUSTEE-TAC",
		"InwxName" => "ACCEPT-TRUSTEE-TAC",
		"Type" => "tickbox",
		"Default" => false,
		"Required" => false,
	);

// .HU
$additionaldomainfields[".hu"] = array();
$additionaldomainfields[".hu"][] = array(
		"DisplayName" => "Trustee service (extra fee could be charged)",
		"Name" => "ACCEPT-TRUSTEE-TAC",
		"InwxName" => "ACCEPT-TRUSTEE-TAC",
		"Type" => "tickbox",
		"Default" => false,
		"Required" => false,
	);

// .IT
$additionaldomainfields[".it"] = array();
$additionaldomainfields[".it"][] = array(
		"DisplayName" => "Trustee service (extra fee could be charged)",
		"Name" => "ACCEPT-TRUSTEE-TAC",
		"InwxName" => "ACCEPT-TRUSTEE-TAC",
		"Type" => "tickbox",
		"Default" => false,
		"Required" => false,
	);

// .NO
$additionaldomainfields[".no"] = array();
$additionaldomainfields[".no"][] = array(
		"DisplayName" => "Trustee service (extra fee could be charged)",
		"Name" => "ACCEPT-TRUSTEE-TAC",
		"InwxName" => "ACCEPT-TRUSTEE-TAC",
		"Type" => "tickbox",
		"Default" => false,
		"Required" => false,
	);

// .SG
$additionaldomainfields[".sg"] = array();
$additionaldomainfields[".sg"][] = array(
		"DisplayName" => "Trustee service (extra fee could be charged)",
		"Name" => "ACCEPT-TRUSTEE-TAC",
		"InwxName" => "ACCEPT-TRUSTEE-TAC",
		"Type" => "tickbox",
		"Default" => false,
		"Required" => false,
	);

// .COM.SG
$additionaldomainfields[".com.sg"] = array();
$additionaldomainfields[".com.sg"][] = array(
		"DisplayName" => "Trustee service (extra fee could be charged)",
		"Name" => "ACCEPT-TRUSTEE-TAC",
		"InwxName" => "ACCEPT-TRUSTEE-TAC",
		"Type" => "tickbox",
		"Default" => false,
		"Required" => false,
	);

// .SK
$additionaldomainfields[".sk"] = array();
$additionaldomainfields[".sk"][] = array(
		"DisplayName" => "Trustee service (extra fee could be charged)",
		"Name" => "ACCEPT-TRUSTEE-TAC",
		"InwxName" => "ACCEPT-TRUSTEE-TAC",
		"Type" => "tickbox",
		"Default" => false,
		"Required" => false,
	);

// .CO.HU
$additionaldomainfields[".co.hu"] = array();
$additionaldomainfields[".co.hu"][] = array(
		"DisplayName" => "Trustee service (extra fee could be charged)",
		"Name" => "ACCEPT-TRUSTEE-TAC",
		"InwxName" => "ACCEPT-TRUSTEE-TAC",
		"Type" => "tickbox",
		"Default" => false,
		"Required" => false,
	);

// .AG.IT
$additionaldomainfields[".ag.it"] = array();
$additionaldomainfields[".ag.it"][] = array(
		"DisplayName" => "Trustee service (extra fee could be charged)",
		"Name" => "ACCEPT-TRUSTEE-TAC",
		"InwxName" => "ACCEPT-TRUSTEE-TAC",
		"Type" => "tickbox",
		"Default" => false,
		"Required" => false,
	);

// .AL.IT
$additionaldomainfields[".al.it"] = array();
$additionaldomainfields[".al.it"][] = array(
		"DisplayName" => "Trustee service (extra fee could be charged)",
		"Name" => "ACCEPT-TRUSTEE-TAC",
		"InwxName" => "ACCEPT-TRUSTEE-TAC",
		"Type" => "tickbox",
		"Default" => false,
		"Required" => false,
	);

// .AN.IT
$additionaldomainfields[".an.it"] = array();
$additionaldomainfields[".an.it"][] = array(
		"DisplayName" => "Trustee service (extra fee could be charged)",
		"Name" => "ACCEPT-TRUSTEE-TAC",
		"InwxName" => "ACCEPT-TRUSTEE-TAC",
		"Type" => "tickbox",
		"Default" => false,
		"Required" => false,
	);

// .AO.IT
$additionaldomainfields[".ao.it"] = array();
$additionaldomainfields[".ao.it"][] = array(
		"DisplayName" => "Trustee service (extra fee could be charged)",
		"Name" => "ACCEPT-TRUSTEE-TAC",
		"InwxName" => "ACCEPT-TRUSTEE-TAC",
		"Type" => "tickbox",
		"Default" => false,
		"Required" => false,
	);

// .AR.IT
$additionaldomainfields[".ar.it"] = array();
$additionaldomainfields[".ar.it"][] = array(
		"DisplayName" => "Trustee service (extra fee could be charged)",
		"Name" => "ACCEPT-TRUSTEE-TAC",
		"InwxName" => "ACCEPT-TRUSTEE-TAC",
		"Type" => "tickbox",
		"Default" => false,
		"Required" => false,
	);

// .AP.IT
$additionaldomainfields[".ap.it"] = array();
$additionaldomainfields[".ap.it"][] = array(
		"DisplayName" => "Trustee service (extra fee could be charged)",
		"Name" => "ACCEPT-TRUSTEE-TAC",
		"InwxName" => "ACCEPT-TRUSTEE-TAC",
		"Type" => "tickbox",
		"Default" => false,
		"Required" => false,
	);

// .AT.IT
$additionaldomainfields[".at.it"] = array();
$additionaldomainfields[".at.it"][] = array(
		"DisplayName" => "Trustee service (extra fee could be charged)",
		"Name" => "ACCEPT-TRUSTEE-TAC",
		"InwxName" => "ACCEPT-TRUSTEE-TAC",
		"Type" => "tickbox",
		"Default" => false,
		"Required" => false,
	);

// .AV.IT
$additionaldomainfields[".av.it"] = array();
$additionaldomainfields[".av.it"][] = array(
		"DisplayName" => "Trustee service (extra fee could be charged)",
		"Name" => "ACCEPT-TRUSTEE-TAC",
		"InwxName" => "ACCEPT-TRUSTEE-TAC",
		"Type" => "tickbox",
		"Default" => false,
		"Required" => false,
	);

// .BA.IT
$additionaldomainfields[".ba.it"] = array();
$additionaldomainfields[".ba.it"][] = array(
		"DisplayName" => "Trustee service (extra fee could be charged)",
		"Name" => "ACCEPT-TRUSTEE-TAC",
		"InwxName" => "ACCEPT-TRUSTEE-TAC",
		"Type" => "tickbox",
		"Default" => false,
		"Required" => false,
	);

// .BT.IT
$additionaldomainfields[".bt.it"] = array();
$additionaldomainfields[".bt.it"][] = array(
		"DisplayName" => "Trustee service (extra fee could be charged)",
		"Name" => "ACCEPT-TRUSTEE-TAC",
		"InwxName" => "ACCEPT-TRUSTEE-TAC",
		"Type" => "tickbox",
		"Default" => false,
		"Required" => false,
	);

// .BL.IT
$additionaldomainfields[".bl.it"] = array();
$additionaldomainfields[".bl.it"][] = array(
		"DisplayName" => "Trustee service (extra fee could be charged)",
		"Name" => "ACCEPT-TRUSTEE-TAC",
		"InwxName" => "ACCEPT-TRUSTEE-TAC",
		"Type" => "tickbox",
		"Default" => false,
		"Required" => false,
	);

// .BN.IT
$additionaldomainfields[".bn.it"] = array();
$additionaldomainfields[".bn.it"][] = array(
		"DisplayName" => "Trustee service (extra fee could be charged)",
		"Name" => "ACCEPT-TRUSTEE-TAC",
		"InwxName" => "ACCEPT-TRUSTEE-TAC",
		"Type" => "tickbox",
		"Default" => false,
		"Required" => false,
	);

// .BG.IT
$additionaldomainfields[".bg.it"] = array();
$additionaldomainfields[".bg.it"][] = array(
		"DisplayName" => "Trustee service (extra fee could be charged)",
		"Name" => "ACCEPT-TRUSTEE-TAC",
		"InwxName" => "ACCEPT-TRUSTEE-TAC",
		"Type" => "tickbox",
		"Default" => false,
		"Required" => false,
	);

// .BI.IT
$additionaldomainfields[".bi.it"] = array();
$additionaldomainfields[".bi.it"][] = array(
		"DisplayName" => "Trustee service (extra fee could be charged)",
		"Name" => "ACCEPT-TRUSTEE-TAC",
		"InwxName" => "ACCEPT-TRUSTEE-TAC",
		"Type" => "tickbox",
		"Default" => false,
		"Required" => false,
	);

// .BO.IT
$additionaldomainfields[".bo.it"] = array();
$additionaldomainfields[".bo.it"][] = array(
		"DisplayName" => "Trustee service (extra fee could be charged)",
		"Name" => "ACCEPT-TRUSTEE-TAC",
		"InwxName" => "ACCEPT-TRUSTEE-TAC",
		"Type" => "tickbox",
		"Default" => false,
		"Required" => false,
	);

// .BZ.IT
$additionaldomainfields[".bz.it"] = array();
$additionaldomainfields[".bz.it"][] = array(
		"DisplayName" => "Trustee service (extra fee could be charged)",
		"Name" => "ACCEPT-TRUSTEE-TAC",
		"InwxName" => "ACCEPT-TRUSTEE-TAC",
		"Type" => "tickbox",
		"Default" => false,
		"Required" => false,
	);

// .BS.IT
$additionaldomainfields[".bs.it"] = array();
$additionaldomainfields[".bs.it"][] = array(
		"DisplayName" => "Trustee service (extra fee could be charged)",
		"Name" => "ACCEPT-TRUSTEE-TAC",
		"InwxName" => "ACCEPT-TRUSTEE-TAC",
		"Type" => "tickbox",
		"Default" => false,
		"Required" => false,
	);

// .BR.IT
$additionaldomainfields[".br.it"] = array();
$additionaldomainfields[".br.it"][] = array(
		"DisplayName" => "Trustee service (extra fee could be charged)",
		"Name" => "ACCEPT-TRUSTEE-TAC",
		"InwxName" => "ACCEPT-TRUSTEE-TAC",
		"Type" => "tickbox",
		"Default" => false,
		"Required" => false,
	);

// .CA.IT
$additionaldomainfields[".ca.it"] = array();
$additionaldomainfields[".ca.it"][] = array(
		"DisplayName" => "Trustee service (extra fee could be charged)",
		"Name" => "ACCEPT-TRUSTEE-TAC",
		"InwxName" => "ACCEPT-TRUSTEE-TAC",
		"Type" => "tickbox",
		"Default" => false,
		"Required" => false,
	);

// .CL.IT
$additionaldomainfields[".cl.it"] = array();
$additionaldomainfields[".cl.it"][] = array(
		"DisplayName" => "Trustee service (extra fee could be charged)",
		"Name" => "ACCEPT-TRUSTEE-TAC",
		"InwxName" => "ACCEPT-TRUSTEE-TAC",
		"Type" => "tickbox",
		"Default" => false,
		"Required" => false,
	);

// .CB.IT
$additionaldomainfields[".cb.it"] = array();
$additionaldomainfields[".cb.it"][] = array(
		"DisplayName" => "Trustee service (extra fee could be charged)",
		"Name" => "ACCEPT-TRUSTEE-TAC",
		"InwxName" => "ACCEPT-TRUSTEE-TAC",
		"Type" => "tickbox",
		"Default" => false,
		"Required" => false,
	);

// .CI.IT
$additionaldomainfields[".ci.it"] = array();
$additionaldomainfields[".ci.it"][] = array(
		"DisplayName" => "Trustee service (extra fee could be charged)",
		"Name" => "ACCEPT-TRUSTEE-TAC",
		"InwxName" => "ACCEPT-TRUSTEE-TAC",
		"Type" => "tickbox",
		"Default" => false,
		"Required" => false,
	);

// .CE.IT
$additionaldomainfields[".ce.it"] = array();
$additionaldomainfields[".ce.it"][] = array(
		"DisplayName" => "Trustee service (extra fee could be charged)",
		"Name" => "ACCEPT-TRUSTEE-TAC",
		"InwxName" => "ACCEPT-TRUSTEE-TAC",
		"Type" => "tickbox",
		"Default" => false,
		"Required" => false,
	);

// .CT.IT
$additionaldomainfields[".ct.it"] = array();
$additionaldomainfields[".ct.it"][] = array(
		"DisplayName" => "Trustee service (extra fee could be charged)",
		"Name" => "ACCEPT-TRUSTEE-TAC",
		"InwxName" => "ACCEPT-TRUSTEE-TAC",
		"Type" => "tickbox",
		"Default" => false,
		"Required" => false,
	);

// .CZ.IT
$additionaldomainfields[".cz.it"] = array();
$additionaldomainfields[".cz.it"][] = array(
		"DisplayName" => "Trustee service (extra fee could be charged)",
		"Name" => "ACCEPT-TRUSTEE-TAC",
		"InwxName" => "ACCEPT-TRUSTEE-TAC",
		"Type" => "tickbox",
		"Default" => false,
		"Required" => false,
	);

// .CH.IT
$additionaldomainfields[".ch.it"] = array();
$additionaldomainfields[".ch.it"][] = array(
		"DisplayName" => "Trustee service (extra fee could be charged)",
		"Name" => "ACCEPT-TRUSTEE-TAC",
		"InwxName" => "ACCEPT-TRUSTEE-TAC",
		"Type" => "tickbox",
		"Default" => false,
		"Required" => false,
	);

// .CO.IT
$additionaldomainfields[".co.it"] = array();
$additionaldomainfields[".co.it"][] = array(
		"DisplayName" => "Trustee service (extra fee could be charged)",
		"Name" => "ACCEPT-TRUSTEE-TAC",
		"InwxName" => "ACCEPT-TRUSTEE-TAC",
		"Type" => "tickbox",
		"Default" => false,
		"Required" => false,
	);

// .CS.IT
$additionaldomainfields[".cs.it"] = array();
$additionaldomainfields[".cs.it"][] = array(
		"DisplayName" => "Trustee service (extra fee could be charged)",
		"Name" => "ACCEPT-TRUSTEE-TAC",
		"InwxName" => "ACCEPT-TRUSTEE-TAC",
		"Type" => "tickbox",
		"Default" => false,
		"Required" => false,
	);

// .CR.IT
$additionaldomainfields[".cr.it"] = array();
$additionaldomainfields[".cr.it"][] = array(
		"DisplayName" => "Trustee service (extra fee could be charged)",
		"Name" => "ACCEPT-TRUSTEE-TAC",
		"InwxName" => "ACCEPT-TRUSTEE-TAC",
		"Type" => "tickbox",
		"Default" => false,
		"Required" => false,
	);

// .KR.IT
$additionaldomainfields[".kr.it"] = array();
$additionaldomainfields[".kr.it"][] = array(
		"DisplayName" => "Trustee service (extra fee could be charged)",
		"Name" => "ACCEPT-TRUSTEE-TAC",
		"InwxName" => "ACCEPT-TRUSTEE-TAC",
		"Type" => "tickbox",
		"Default" => false,
		"Required" => false,
	);

// .CN.IT
$additionaldomainfields[".cn.it"] = array();
$additionaldomainfields[".cn.it"][] = array(
		"DisplayName" => "Trustee service (extra fee could be charged)",
		"Name" => "ACCEPT-TRUSTEE-TAC",
		"InwxName" => "ACCEPT-TRUSTEE-TAC",
		"Type" => "tickbox",
		"Default" => false,
		"Required" => false,
	);

// .OG.IT
$additionaldomainfields[".og.it"] = array();
$additionaldomainfields[".og.it"][] = array(
		"DisplayName" => "Trustee service (extra fee could be charged)",
		"Name" => "ACCEPT-TRUSTEE-TAC",
		"InwxName" => "ACCEPT-TRUSTEE-TAC",
		"Type" => "tickbox",
		"Default" => false,
		"Required" => false,
	);

// .EN.IT
$additionaldomainfields[".en.it"] = array();
$additionaldomainfields[".en.it"][] = array(
		"DisplayName" => "Trustee service (extra fee could be charged)",
		"Name" => "ACCEPT-TRUSTEE-TAC",
		"InwxName" => "ACCEPT-TRUSTEE-TAC",
		"Type" => "tickbox",
		"Default" => false,
		"Required" => false,
	);

// .FE.IT
$additionaldomainfields[".fe.it"] = array();
$additionaldomainfields[".fe.it"][] = array(
		"DisplayName" => "Trustee service (extra fee could be charged)",
		"Name" => "ACCEPT-TRUSTEE-TAC",
		"InwxName" => "ACCEPT-TRUSTEE-TAC",
		"Type" => "tickbox",
		"Default" => false,
		"Required" => false,
	);

// .FM.IT
$additionaldomainfields[".fm.it"] = array();
$additionaldomainfields[".fm.it"][] = array(
		"DisplayName" => "Trustee service (extra fee could be charged)",
		"Name" => "ACCEPT-TRUSTEE-TAC",
		"InwxName" => "ACCEPT-TRUSTEE-TAC",
		"Type" => "tickbox",
		"Default" => false,
		"Required" => false,
	);

// .FI.IT
$additionaldomainfields[".fi.it"] = array();
$additionaldomainfields[".fi.it"][] = array(
		"DisplayName" => "Trustee service (extra fee could be charged)",
		"Name" => "ACCEPT-TRUSTEE-TAC",
		"InwxName" => "ACCEPT-TRUSTEE-TAC",
		"Type" => "tickbox",
		"Default" => false,
		"Required" => false,
	);

// .FG.IT
$additionaldomainfields[".fg.it"] = array();
$additionaldomainfields[".fg.it"][] = array(
		"DisplayName" => "Trustee service (extra fee could be charged)",
		"Name" => "ACCEPT-TRUSTEE-TAC",
		"InwxName" => "ACCEPT-TRUSTEE-TAC",
		"Type" => "tickbox",
		"Default" => false,
		"Required" => false,
	);

// .FC.IT
$additionaldomainfields[".fc.it"] = array();
$additionaldomainfields[".fc.it"][] = array(
		"DisplayName" => "Trustee service (extra fee could be charged)",
		"Name" => "ACCEPT-TRUSTEE-TAC",
		"InwxName" => "ACCEPT-TRUSTEE-TAC",
		"Type" => "tickbox",
		"Default" => false,
		"Required" => false,
	);

// .FR.IT
$additionaldomainfields[".fr.it"] = array();
$additionaldomainfields[".fr.it"][] = array(
		"DisplayName" => "Trustee service (extra fee could be charged)",
		"Name" => "ACCEPT-TRUSTEE-TAC",
		"InwxName" => "ACCEPT-TRUSTEE-TAC",
		"Type" => "tickbox",
		"Default" => false,
		"Required" => false,
	);

// .GE.IT
$additionaldomainfields[".ge.it"] = array();
$additionaldomainfields[".ge.it"][] = array(
		"DisplayName" => "Trustee service (extra fee could be charged)",
		"Name" => "ACCEPT-TRUSTEE-TAC",
		"InwxName" => "ACCEPT-TRUSTEE-TAC",
		"Type" => "tickbox",
		"Default" => false,
		"Required" => false,
	);

// .GO.IT
$additionaldomainfields[".go.it"] = array();
$additionaldomainfields[".go.it"][] = array(
		"DisplayName" => "Trustee service (extra fee could be charged)",
		"Name" => "ACCEPT-TRUSTEE-TAC",
		"InwxName" => "ACCEPT-TRUSTEE-TAC",
		"Type" => "tickbox",
		"Default" => false,
		"Required" => false,
	);

// .GR.IT
$additionaldomainfields[".gr.it"] = array();
$additionaldomainfields[".gr.it"][] = array(
		"DisplayName" => "Trustee service (extra fee could be charged)",
		"Name" => "ACCEPT-TRUSTEE-TAC",
		"InwxName" => "ACCEPT-TRUSTEE-TAC",
		"Type" => "tickbox",
		"Default" => false,
		"Required" => false,
	);

// .IM.IT
$additionaldomainfields[".im.it"] = array();
$additionaldomainfields[".im.it"][] = array(
		"DisplayName" => "Trustee service (extra fee could be charged)",
		"Name" => "ACCEPT-TRUSTEE-TAC",
		"InwxName" => "ACCEPT-TRUSTEE-TAC",
		"Type" => "tickbox",
		"Default" => false,
		"Required" => false,
	);

// .IS.IT
$additionaldomainfields[".is.it"] = array();
$additionaldomainfields[".is.it"][] = array(
		"DisplayName" => "Trustee service (extra fee could be charged)",
		"Name" => "ACCEPT-TRUSTEE-TAC",
		"InwxName" => "ACCEPT-TRUSTEE-TAC",
		"Type" => "tickbox",
		"Default" => false,
		"Required" => false,
	);

// .AQ.IT
$additionaldomainfields[".aq.it"] = array();
$additionaldomainfields[".aq.it"][] = array(
		"DisplayName" => "Trustee service (extra fee could be charged)",
		"Name" => "ACCEPT-TRUSTEE-TAC",
		"InwxName" => "ACCEPT-TRUSTEE-TAC",
		"Type" => "tickbox",
		"Default" => false,
		"Required" => false,
	);

// .SP.IT
$additionaldomainfields[".sp.it"] = array();
$additionaldomainfields[".sp.it"][] = array(
		"DisplayName" => "Trustee service (extra fee could be charged)",
		"Name" => "ACCEPT-TRUSTEE-TAC",
		"InwxName" => "ACCEPT-TRUSTEE-TAC",
		"Type" => "tickbox",
		"Default" => false,
		"Required" => false,
	);

// .LT.IT
$additionaldomainfields[".lt.it"] = array();
$additionaldomainfields[".lt.it"][] = array(
		"DisplayName" => "Trustee service (extra fee could be charged)",
		"Name" => "ACCEPT-TRUSTEE-TAC",
		"InwxName" => "ACCEPT-TRUSTEE-TAC",
		"Type" => "tickbox",
		"Default" => false,
		"Required" => false,
	);

// .LE.IT
$additionaldomainfields[".le.it"] = array();
$additionaldomainfields[".le.it"][] = array(
		"DisplayName" => "Trustee service (extra fee could be charged)",
		"Name" => "ACCEPT-TRUSTEE-TAC",
		"InwxName" => "ACCEPT-TRUSTEE-TAC",
		"Type" => "tickbox",
		"Default" => false,
		"Required" => false,
	);

// .LC.IT
$additionaldomainfields[".lc.it"] = array();
$additionaldomainfields[".lc.it"][] = array(
		"DisplayName" => "Trustee service (extra fee could be charged)",
		"Name" => "ACCEPT-TRUSTEE-TAC",
		"InwxName" => "ACCEPT-TRUSTEE-TAC",
		"Type" => "tickbox",
		"Default" => false,
		"Required" => false,
	);

// .LI.IT
$additionaldomainfields[".li.it"] = array();
$additionaldomainfields[".li.it"][] = array(
		"DisplayName" => "Trustee service (extra fee could be charged)",
		"Name" => "ACCEPT-TRUSTEE-TAC",
		"InwxName" => "ACCEPT-TRUSTEE-TAC",
		"Type" => "tickbox",
		"Default" => false,
		"Required" => false,
	);

// .LO.IT
$additionaldomainfields[".lo.it"] = array();
$additionaldomainfields[".lo.it"][] = array(
		"DisplayName" => "Trustee service (extra fee could be charged)",
		"Name" => "ACCEPT-TRUSTEE-TAC",
		"InwxName" => "ACCEPT-TRUSTEE-TAC",
		"Type" => "tickbox",
		"Default" => false,
		"Required" => false,
	);

// .LU.IT
$additionaldomainfields[".lu.it"] = array();
$additionaldomainfields[".lu.it"][] = array(
		"DisplayName" => "Trustee service (extra fee could be charged)",
		"Name" => "ACCEPT-TRUSTEE-TAC",
		"InwxName" => "ACCEPT-TRUSTEE-TAC",
		"Type" => "tickbox",
		"Default" => false,
		"Required" => false,
	);

// .MC.IT
$additionaldomainfields[".mc.it"] = array();
$additionaldomainfields[".mc.it"][] = array(
		"DisplayName" => "Trustee service (extra fee could be charged)",
		"Name" => "ACCEPT-TRUSTEE-TAC",
		"InwxName" => "ACCEPT-TRUSTEE-TAC",
		"Type" => "tickbox",
		"Default" => false,
		"Required" => false,
	);

// .MN.IT
$additionaldomainfields[".mn.it"] = array();
$additionaldomainfields[".mn.it"][] = array(
		"DisplayName" => "Trustee service (extra fee could be charged)",
		"Name" => "ACCEPT-TRUSTEE-TAC",
		"InwxName" => "ACCEPT-TRUSTEE-TAC",
		"Type" => "tickbox",
		"Default" => false,
		"Required" => false,
	);

// .MS.IT
$additionaldomainfields[".ms.it"] = array();
$additionaldomainfields[".ms.it"][] = array(
		"DisplayName" => "Trustee service (extra fee could be charged)",
		"Name" => "ACCEPT-TRUSTEE-TAC",
		"InwxName" => "ACCEPT-TRUSTEE-TAC",
		"Type" => "tickbox",
		"Default" => false,
		"Required" => false,
	);

// .MT.IT
$additionaldomainfields[".mt.it"] = array();
$additionaldomainfields[".mt.it"][] = array(
		"DisplayName" => "Trustee service (extra fee could be charged)",
		"Name" => "ACCEPT-TRUSTEE-TAC",
		"InwxName" => "ACCEPT-TRUSTEE-TAC",
		"Type" => "tickbox",
		"Default" => false,
		"Required" => false,
	);

// .VS.IT
$additionaldomainfields[".vs.it"] = array();
$additionaldomainfields[".vs.it"][] = array(
		"DisplayName" => "Trustee service (extra fee could be charged)",
		"Name" => "ACCEPT-TRUSTEE-TAC",
		"InwxName" => "ACCEPT-TRUSTEE-TAC",
		"Type" => "tickbox",
		"Default" => false,
		"Required" => false,
	);

// .ME.IT
$additionaldomainfields[".me.it"] = array();
$additionaldomainfields[".me.it"][] = array(
		"DisplayName" => "Trustee service (extra fee could be charged)",
		"Name" => "ACCEPT-TRUSTEE-TAC",
		"InwxName" => "ACCEPT-TRUSTEE-TAC",
		"Type" => "tickbox",
		"Default" => false,
		"Required" => false,
	);

// .MI.IT
$additionaldomainfields[".mi.it"] = array();
$additionaldomainfields[".mi.it"][] = array(
		"DisplayName" => "Trustee service (extra fee could be charged)",
		"Name" => "ACCEPT-TRUSTEE-TAC",
		"InwxName" => "ACCEPT-TRUSTEE-TAC",
		"Type" => "tickbox",
		"Default" => false,
		"Required" => false,
	);

// .MO.IT
$additionaldomainfields[".mo.it"] = array();
$additionaldomainfields[".mo.it"][] = array(
		"DisplayName" => "Trustee service (extra fee could be charged)",
		"Name" => "ACCEPT-TRUSTEE-TAC",
		"InwxName" => "ACCEPT-TRUSTEE-TAC",
		"Type" => "tickbox",
		"Default" => false,
		"Required" => false,
	);

// .MB.IT
$additionaldomainfields[".mb.it"] = array();
$additionaldomainfields[".mb.it"][] = array(
		"DisplayName" => "Trustee service (extra fee could be charged)",
		"Name" => "ACCEPT-TRUSTEE-TAC",
		"InwxName" => "ACCEPT-TRUSTEE-TAC",
		"Type" => "tickbox",
		"Default" => false,
		"Required" => false,
	);

// .NA.IT
$additionaldomainfields[".na.it"] = array();
$additionaldomainfields[".na.it"][] = array(
		"DisplayName" => "Trustee service (extra fee could be charged)",
		"Name" => "ACCEPT-TRUSTEE-TAC",
		"InwxName" => "ACCEPT-TRUSTEE-TAC",
		"Type" => "tickbox",
		"Default" => false,
		"Required" => false,
	);

// .NO.IT
$additionaldomainfields[".no.it"] = array();
$additionaldomainfields[".no.it"][] = array(
		"DisplayName" => "Trustee service (extra fee could be charged)",
		"Name" => "ACCEPT-TRUSTEE-TAC",
		"InwxName" => "ACCEPT-TRUSTEE-TAC",
		"Type" => "tickbox",
		"Default" => false,
		"Required" => false,
	);

// .NU.IT
$additionaldomainfields[".nu.it"] = array();
$additionaldomainfields[".nu.it"][] = array(
		"DisplayName" => "Trustee service (extra fee could be charged)",
		"Name" => "ACCEPT-TRUSTEE-TAC",
		"InwxName" => "ACCEPT-TRUSTEE-TAC",
		"Type" => "tickbox",
		"Default" => false,
		"Required" => false,
	);

// .OR.IT
$additionaldomainfields[".or.it"] = array();
$additionaldomainfields[".or.it"][] = array(
		"DisplayName" => "Trustee service (extra fee could be charged)",
		"Name" => "ACCEPT-TRUSTEE-TAC",
		"InwxName" => "ACCEPT-TRUSTEE-TAC",
		"Type" => "tickbox",
		"Default" => false,
		"Required" => false,
	);

// .PD.IT
$additionaldomainfields[".pd.it"] = array();
$additionaldomainfields[".pd.it"][] = array(
		"DisplayName" => "Trustee service (extra fee could be charged)",
		"Name" => "ACCEPT-TRUSTEE-TAC",
		"InwxName" => "ACCEPT-TRUSTEE-TAC",
		"Type" => "tickbox",
		"Default" => false,
		"Required" => false,
	);

// .PA.IT
$additionaldomainfields[".pa.it"] = array();
$additionaldomainfields[".pa.it"][] = array(
		"DisplayName" => "Trustee service (extra fee could be charged)",
		"Name" => "ACCEPT-TRUSTEE-TAC",
		"InwxName" => "ACCEPT-TRUSTEE-TAC",
		"Type" => "tickbox",
		"Default" => false,
		"Required" => false,
	);

// .PR.IT
$additionaldomainfields[".pr.it"] = array();
$additionaldomainfields[".pr.it"][] = array(
		"DisplayName" => "Trustee service (extra fee could be charged)",
		"Name" => "ACCEPT-TRUSTEE-TAC",
		"InwxName" => "ACCEPT-TRUSTEE-TAC",
		"Type" => "tickbox",
		"Default" => false,
		"Required" => false,
	);

// .PV.IT
$additionaldomainfields[".pv.it"] = array();
$additionaldomainfields[".pv.it"][] = array(
		"DisplayName" => "Trustee service (extra fee could be charged)",
		"Name" => "ACCEPT-TRUSTEE-TAC",
		"InwxName" => "ACCEPT-TRUSTEE-TAC",
		"Type" => "tickbox",
		"Default" => false,
		"Required" => false,
	);

// .PG.IT
$additionaldomainfields[".pg.it"] = array();
$additionaldomainfields[".pg.it"][] = array(
		"DisplayName" => "Trustee service (extra fee could be charged)",
		"Name" => "ACCEPT-TRUSTEE-TAC",
		"InwxName" => "ACCEPT-TRUSTEE-TAC",
		"Type" => "tickbox",
		"Default" => false,
		"Required" => false,
	);

// .PE.IT
$additionaldomainfields[".pe.it"] = array();
$additionaldomainfields[".pe.it"][] = array(
		"DisplayName" => "Trustee service (extra fee could be charged)",
		"Name" => "ACCEPT-TRUSTEE-TAC",
		"InwxName" => "ACCEPT-TRUSTEE-TAC",
		"Type" => "tickbox",
		"Default" => false,
		"Required" => false,
	);

// .PU.IT
$additionaldomainfields[".pu.it"] = array();
$additionaldomainfields[".pu.it"][] = array(
		"DisplayName" => "Trustee service (extra fee could be charged)",
		"Name" => "ACCEPT-TRUSTEE-TAC",
		"InwxName" => "ACCEPT-TRUSTEE-TAC",
		"Type" => "tickbox",
		"Default" => false,
		"Required" => false,
	);

// .PC.IT
$additionaldomainfields[".pc.it"] = array();
$additionaldomainfields[".pc.it"][] = array(
		"DisplayName" => "Trustee service (extra fee could be charged)",
		"Name" => "ACCEPT-TRUSTEE-TAC",
		"InwxName" => "ACCEPT-TRUSTEE-TAC",
		"Type" => "tickbox",
		"Default" => false,
		"Required" => false,
	);

// .PI.IT
$additionaldomainfields[".pi.it"] = array();
$additionaldomainfields[".pi.it"][] = array(
		"DisplayName" => "Trustee service (extra fee could be charged)",
		"Name" => "ACCEPT-TRUSTEE-TAC",
		"InwxName" => "ACCEPT-TRUSTEE-TAC",
		"Type" => "tickbox",
		"Default" => false,
		"Required" => false,
	);

// .PT.IT
$additionaldomainfields[".pt.it"] = array();
$additionaldomainfields[".pt.it"][] = array(
		"DisplayName" => "Trustee service (extra fee could be charged)",
		"Name" => "ACCEPT-TRUSTEE-TAC",
		"InwxName" => "ACCEPT-TRUSTEE-TAC",
		"Type" => "tickbox",
		"Default" => false,
		"Required" => false,
	);

// .PN.IT
$additionaldomainfields[".pn.it"] = array();
$additionaldomainfields[".pn.it"][] = array(
		"DisplayName" => "Trustee service (extra fee could be charged)",
		"Name" => "ACCEPT-TRUSTEE-TAC",
		"InwxName" => "ACCEPT-TRUSTEE-TAC",
		"Type" => "tickbox",
		"Default" => false,
		"Required" => false,
	);

// .PZ.IT
$additionaldomainfields[".pz.it"] = array();
$additionaldomainfields[".pz.it"][] = array(
		"DisplayName" => "Trustee service (extra fee could be charged)",
		"Name" => "ACCEPT-TRUSTEE-TAC",
		"InwxName" => "ACCEPT-TRUSTEE-TAC",
		"Type" => "tickbox",
		"Default" => false,
		"Required" => false,
	);

// .PO.IT
$additionaldomainfields[".po.it"] = array();
$additionaldomainfields[".po.it"][] = array(
		"DisplayName" => "Trustee service (extra fee could be charged)",
		"Name" => "ACCEPT-TRUSTEE-TAC",
		"InwxName" => "ACCEPT-TRUSTEE-TAC",
		"Type" => "tickbox",
		"Default" => false,
		"Required" => false,
	);

// .RG.IT
$additionaldomainfields[".rg.it"] = array();
$additionaldomainfields[".rg.it"][] = array(
		"DisplayName" => "Trustee service (extra fee could be charged)",
		"Name" => "ACCEPT-TRUSTEE-TAC",
		"InwxName" => "ACCEPT-TRUSTEE-TAC",
		"Type" => "tickbox",
		"Default" => false,
		"Required" => false,
	);

// .RA.IT
$additionaldomainfields[".ra.it"] = array();
$additionaldomainfields[".ra.it"][] = array(
		"DisplayName" => "Trustee service (extra fee could be charged)",
		"Name" => "ACCEPT-TRUSTEE-TAC",
		"InwxName" => "ACCEPT-TRUSTEE-TAC",
		"Type" => "tickbox",
		"Default" => false,
		"Required" => false,
	);

// .RC.IT
$additionaldomainfields[".rc.it"] = array();
$additionaldomainfields[".rc.it"][] = array(
		"DisplayName" => "Trustee service (extra fee could be charged)",
		"Name" => "ACCEPT-TRUSTEE-TAC",
		"InwxName" => "ACCEPT-TRUSTEE-TAC",
		"Type" => "tickbox",
		"Default" => false,
		"Required" => false,
	);

// .RE.IT
$additionaldomainfields[".re.it"] = array();
$additionaldomainfields[".re.it"][] = array(
		"DisplayName" => "Trustee service (extra fee could be charged)",
		"Name" => "ACCEPT-TRUSTEE-TAC",
		"InwxName" => "ACCEPT-TRUSTEE-TAC",
		"Type" => "tickbox",
		"Default" => false,
		"Required" => false,
	);

// .RI.IT
$additionaldomainfields[".ri.it"] = array();
$additionaldomainfields[".ri.it"][] = array(
		"DisplayName" => "Trustee service (extra fee could be charged)",
		"Name" => "ACCEPT-TRUSTEE-TAC",
		"InwxName" => "ACCEPT-TRUSTEE-TAC",
		"Type" => "tickbox",
		"Default" => false,
		"Required" => false,
	);

// .RN.IT
$additionaldomainfields[".rn.it"] = array();
$additionaldomainfields[".rn.it"][] = array(
		"DisplayName" => "Trustee service (extra fee could be charged)",
		"Name" => "ACCEPT-TRUSTEE-TAC",
		"InwxName" => "ACCEPT-TRUSTEE-TAC",
		"Type" => "tickbox",
		"Default" => false,
		"Required" => false,
	);

// .RM.IT
$additionaldomainfields[".rm.it"] = array();
$additionaldomainfields[".rm.it"][] = array(
		"DisplayName" => "Trustee service (extra fee could be charged)",
		"Name" => "ACCEPT-TRUSTEE-TAC",
		"InwxName" => "ACCEPT-TRUSTEE-TAC",
		"Type" => "tickbox",
		"Default" => false,
		"Required" => false,
	);

// .RO.IT
$additionaldomainfields[".ro.it"] = array();
$additionaldomainfields[".ro.it"][] = array(
		"DisplayName" => "Trustee service (extra fee could be charged)",
		"Name" => "ACCEPT-TRUSTEE-TAC",
		"InwxName" => "ACCEPT-TRUSTEE-TAC",
		"Type" => "tickbox",
		"Default" => false,
		"Required" => false,
	);

// .SA.IT
$additionaldomainfields[".sa.it"] = array();
$additionaldomainfields[".sa.it"][] = array(
		"DisplayName" => "Trustee service (extra fee could be charged)",
		"Name" => "ACCEPT-TRUSTEE-TAC",
		"InwxName" => "ACCEPT-TRUSTEE-TAC",
		"Type" => "tickbox",
		"Default" => false,
		"Required" => false,
	);

// .SS.IT
$additionaldomainfields[".ss.it"] = array();
$additionaldomainfields[".ss.it"][] = array(
		"DisplayName" => "Trustee service (extra fee could be charged)",
		"Name" => "ACCEPT-TRUSTEE-TAC",
		"InwxName" => "ACCEPT-TRUSTEE-TAC",
		"Type" => "tickbox",
		"Default" => false,
		"Required" => false,
	);

// .SV.IT
$additionaldomainfields[".sv.it"] = array();
$additionaldomainfields[".sv.it"][] = array(
		"DisplayName" => "Trustee service (extra fee could be charged)",
		"Name" => "ACCEPT-TRUSTEE-TAC",
		"InwxName" => "ACCEPT-TRUSTEE-TAC",
		"Type" => "tickbox",
		"Default" => false,
		"Required" => false,
	);

// .SI.IT
$additionaldomainfields[".si.it"] = array();
$additionaldomainfields[".si.it"][] = array(
		"DisplayName" => "Trustee service (extra fee could be charged)",
		"Name" => "ACCEPT-TRUSTEE-TAC",
		"InwxName" => "ACCEPT-TRUSTEE-TAC",
		"Type" => "tickbox",
		"Default" => false,
		"Required" => false,
	);

// .SR.IT
$additionaldomainfields[".sr.it"] = array();
$additionaldomainfields[".sr.it"][] = array(
		"DisplayName" => "Trustee service (extra fee could be charged)",
		"Name" => "ACCEPT-TRUSTEE-TAC",
		"InwxName" => "ACCEPT-TRUSTEE-TAC",
		"Type" => "tickbox",
		"Default" => false,
		"Required" => false,
	);

// .SO.IT
$additionaldomainfields[".so.it"] = array();
$additionaldomainfields[".so.it"][] = array(
		"DisplayName" => "Trustee service (extra fee could be charged)",
		"Name" => "ACCEPT-TRUSTEE-TAC",
		"InwxName" => "ACCEPT-TRUSTEE-TAC",
		"Type" => "tickbox",
		"Default" => false,
		"Required" => false,
	);

// .TA.IT
$additionaldomainfields[".ta.it"] = array();
$additionaldomainfields[".ta.it"][] = array(
		"DisplayName" => "Trustee service (extra fee could be charged)",
		"Name" => "ACCEPT-TRUSTEE-TAC",
		"InwxName" => "ACCEPT-TRUSTEE-TAC",
		"Type" => "tickbox",
		"Default" => false,
		"Required" => false,
	);

// .OT.IT
$additionaldomainfields[".ot.it"] = array();
$additionaldomainfields[".ot.it"][] = array(
		"DisplayName" => "Trustee service (extra fee could be charged)",
		"Name" => "ACCEPT-TRUSTEE-TAC",
		"InwxName" => "ACCEPT-TRUSTEE-TAC",
		"Type" => "tickbox",
		"Default" => false,
		"Required" => false,
	);

// .TE.IT
$additionaldomainfields[".te.it"] = array();
$additionaldomainfields[".te.it"][] = array(
		"DisplayName" => "Trustee service (extra fee could be charged)",
		"Name" => "ACCEPT-TRUSTEE-TAC",
		"InwxName" => "ACCEPT-TRUSTEE-TAC",
		"Type" => "tickbox",
		"Default" => false,
		"Required" => false,
	);

// .TR.IT
$additionaldomainfields[".tr.it"] = array();
$additionaldomainfields[".tr.it"][] = array(
		"DisplayName" => "Trustee service (extra fee could be charged)",
		"Name" => "ACCEPT-TRUSTEE-TAC",
		"InwxName" => "ACCEPT-TRUSTEE-TAC",
		"Type" => "tickbox",
		"Default" => false,
		"Required" => false,
	);

// .TO.IT
$additionaldomainfields[".to.it"] = array();
$additionaldomainfields[".to.it"][] = array(
		"DisplayName" => "Trustee service (extra fee could be charged)",
		"Name" => "ACCEPT-TRUSTEE-TAC",
		"InwxName" => "ACCEPT-TRUSTEE-TAC",
		"Type" => "tickbox",
		"Default" => false,
		"Required" => false,
	);

// .TP.IT
$additionaldomainfields[".tp.it"] = array();
$additionaldomainfields[".tp.it"][] = array(
		"DisplayName" => "Trustee service (extra fee could be charged)",
		"Name" => "ACCEPT-TRUSTEE-TAC",
		"InwxName" => "ACCEPT-TRUSTEE-TAC",
		"Type" => "tickbox",
		"Default" => false,
		"Required" => false,
	);

// .TN.IT
$additionaldomainfields[".tn.it"] = array();
$additionaldomainfields[".tn.it"][] = array(
		"DisplayName" => "Trustee service (extra fee could be charged)",
		"Name" => "ACCEPT-TRUSTEE-TAC",
		"InwxName" => "ACCEPT-TRUSTEE-TAC",
		"Type" => "tickbox",
		"Default" => false,
		"Required" => false,
	);

// .TV.IT
$additionaldomainfields[".tv.it"] = array();
$additionaldomainfields[".tv.it"][] = array(
		"DisplayName" => "Trustee service (extra fee could be charged)",
		"Name" => "ACCEPT-TRUSTEE-TAC",
		"InwxName" => "ACCEPT-TRUSTEE-TAC",
		"Type" => "tickbox",
		"Default" => false,
		"Required" => false,
	);

// .TS.IT
$additionaldomainfields[".ts.it"] = array();
$additionaldomainfields[".ts.it"][] = array(
		"DisplayName" => "Trustee service (extra fee could be charged)",
		"Name" => "ACCEPT-TRUSTEE-TAC",
		"InwxName" => "ACCEPT-TRUSTEE-TAC",
		"Type" => "tickbox",
		"Default" => false,
		"Required" => false,
	);

// .UD.IT
$additionaldomainfields[".ud.it"] = array();
$additionaldomainfields[".ud.it"][] = array(
		"DisplayName" => "Trustee service (extra fee could be charged)",
		"Name" => "ACCEPT-TRUSTEE-TAC",
		"InwxName" => "ACCEPT-TRUSTEE-TAC",
		"Type" => "tickbox",
		"Default" => false,
		"Required" => false,
	);

// .VA.IT
$additionaldomainfields[".va.it"] = array();
$additionaldomainfields[".va.it"][] = array(
		"DisplayName" => "Trustee service (extra fee could be charged)",
		"Name" => "ACCEPT-TRUSTEE-TAC",
		"InwxName" => "ACCEPT-TRUSTEE-TAC",
		"Type" => "tickbox",
		"Default" => false,
		"Required" => false,
	);

// .VE.IT
$additionaldomainfields[".ve.it"] = array();
$additionaldomainfields[".ve.it"][] = array(
		"DisplayName" => "Trustee service (extra fee could be charged)",
		"Name" => "ACCEPT-TRUSTEE-TAC",
		"InwxName" => "ACCEPT-TRUSTEE-TAC",
		"Type" => "tickbox",
		"Default" => false,
		"Required" => false,
	);

// .VB.IT
$additionaldomainfields[".vb.it"] = array();
$additionaldomainfields[".vb.it"][] = array(
		"DisplayName" => "Trustee service (extra fee could be charged)",
		"Name" => "ACCEPT-TRUSTEE-TAC",
		"InwxName" => "ACCEPT-TRUSTEE-TAC",
		"Type" => "tickbox",
		"Default" => false,
		"Required" => false,
	);

// .VC.IT
$additionaldomainfields[".vc.it"] = array();
$additionaldomainfields[".vc.it"][] = array(
		"DisplayName" => "Trustee service (extra fee could be charged)",
		"Name" => "ACCEPT-TRUSTEE-TAC",
		"InwxName" => "ACCEPT-TRUSTEE-TAC",
		"Type" => "tickbox",
		"Default" => false,
		"Required" => false,
	);

// .VR.IT
$additionaldomainfields[".vr.it"] = array();
$additionaldomainfields[".vr.it"][] = array(
		"DisplayName" => "Trustee service (extra fee could be charged)",
		"Name" => "ACCEPT-TRUSTEE-TAC",
		"InwxName" => "ACCEPT-TRUSTEE-TAC",
		"Type" => "tickbox",
		"Default" => false,
		"Required" => false,
	);

// .VV.IT
$additionaldomainfields[".vv.it"] = array();
$additionaldomainfields[".vv.it"][] = array(
		"DisplayName" => "Trustee service (extra fee could be charged)",
		"Name" => "ACCEPT-TRUSTEE-TAC",
		"InwxName" => "ACCEPT-TRUSTEE-TAC",
		"Type" => "tickbox",
		"Default" => false,
		"Required" => false,
	);

// .VI.IT
$additionaldomainfields[".vi.it"] = array();
$additionaldomainfields[".vi.it"][] = array(
		"DisplayName" => "Trustee service (extra fee could be charged)",
		"Name" => "ACCEPT-TRUSTEE-TAC",
		"InwxName" => "ACCEPT-TRUSTEE-TAC",
		"Type" => "tickbox",
		"Default" => false,
		"Required" => false,
	);

// .VT.IT
$additionaldomainfields[".vt.it"] = array();
$additionaldomainfields[".vt.it"][] = array(
		"DisplayName" => "Trustee service (extra fee could be charged)",
		"Name" => "ACCEPT-TRUSTEE-TAC",
		"InwxName" => "ACCEPT-TRUSTEE-TAC",
		"Type" => "tickbox",
		"Default" => false,
		"Required" => false,
	);

// .AX
$additionaldomainfields[".ax"] = array();
$additionaldomainfields[".ax"][] = array(
		"DisplayName" => "Trustee service (extra fee could be charged)",
		"Name" => "ACCEPT-TRUSTEE-TAC",
		"InwxName" => "ACCEPT-TRUSTEE-TAC",
		"Type" => "tickbox",
		"Default" => false,
		"Required" => false,
	);

// .COM.BH
$additionaldomainfields[".com.bh"] = array();
$additionaldomainfields[".com.bh"][] = array(
		"DisplayName" => "Trustee service (extra fee could be charged)",
		"Name" => "ACCEPT-TRUSTEE-TAC",
		"InwxName" => "ACCEPT-TRUSTEE-TAC",
		"Type" => "tickbox",
		"Default" => false,
		"Required" => false,
	);

// .COM.FR
$additionaldomainfields[".com.fr"] = array();
$additionaldomainfields[".com.fr"][] = array(
		"DisplayName" => "Trustee service (extra fee could be charged)",
		"Name" => "ACCEPT-TRUSTEE-TAC",
		"InwxName" => "ACCEPT-TRUSTEE-TAC",
		"Type" => "tickbox",
		"Default" => false,
		"Required" => false,
	);

// .COM.PY
$additionaldomainfields[".com.py"] = array();
$additionaldomainfields[".com.py"][] = array(
		"DisplayName" => "Trustee service (extra fee could be charged)",
		"Name" => "ACCEPT-TRUSTEE-TAC",
		"InwxName" => "ACCEPT-TRUSTEE-TAC",
		"Type" => "tickbox",
		"Default" => false,
		"Required" => false,
	);

// .CU
$additionaldomainfields[".cu"] = array();
$additionaldomainfields[".cu"][] = array(
		"DisplayName" => "Trustee service (extra fee could be charged)",
		"Name" => "ACCEPT-TRUSTEE-TAC",
		"InwxName" => "ACCEPT-TRUSTEE-TAC",
		"Type" => "tickbox",
		"Default" => false,
		"Required" => false,
	);

// .JO
$additionaldomainfields[".jo"] = array();
$additionaldomainfields[".jo"][] = array(
		"DisplayName" => "Trustee service (extra fee could be charged)",
		"Name" => "ACCEPT-TRUSTEE-TAC",
		"InwxName" => "ACCEPT-TRUSTEE-TAC",
		"Type" => "tickbox",
		"Default" => false,
		"Required" => false,
	);

// .KR
$additionaldomainfields[".kr"] = array();
$additionaldomainfields[".kr"][] = array(
		"DisplayName" => "Trustee service (extra fee could be charged)",
		"Name" => "ACCEPT-TRUSTEE-TAC",
		"InwxName" => "ACCEPT-TRUSTEE-TAC",
		"Type" => "tickbox",
		"Default" => false,
		"Required" => false,
	);

// .MY
$additionaldomainfields[".my"] = array();
$additionaldomainfields[".my"][] = array(
		"DisplayName" => "Trustee service (extra fee could be charged)",
		"Name" => "ACCEPT-TRUSTEE-TAC",
		"InwxName" => "ACCEPT-TRUSTEE-TAC",
		"Type" => "tickbox",
		"Default" => false,
		"Required" => false,
	);

// .NET.BR
$additionaldomainfields[".net.br"] = array();
$additionaldomainfields[".net.br"][] = array(
		"DisplayName" => "Trustee service (extra fee could be charged)",
		"Name" => "ACCEPT-TRUSTEE-TAC",
		"InwxName" => "ACCEPT-TRUSTEE-TAC",
		"Type" => "tickbox",
		"Default" => false,
		"Required" => false,
	);

// .RE
$additionaldomainfields[".re"] = array();
$additionaldomainfields[".re"][] = array(
		"DisplayName" => "Trustee service (extra fee could be charged)",
		"Name" => "ACCEPT-TRUSTEE-TAC",
		"InwxName" => "ACCEPT-TRUSTEE-TAC",
		"Type" => "tickbox",
		"Default" => false,
		"Required" => false,
	);

// .COM.MY
$additionaldomainfields[".com.my"] = array();
$additionaldomainfields[".com.my"][] = array(
		"DisplayName" => "Trustee service (extra fee could be charged)",
		"Name" => "ACCEPT-TRUSTEE-TAC",
		"InwxName" => "ACCEPT-TRUSTEE-TAC",
		"Type" => "tickbox",
		"Default" => false,
		"Required" => false,
	);

// .NET.MY
$additionaldomainfields[".net.my"] = array();
$additionaldomainfields[".net.my"][] = array(
		"DisplayName" => "Trustee service (extra fee could be charged)",
		"Name" => "ACCEPT-TRUSTEE-TAC",
		"InwxName" => "ACCEPT-TRUSTEE-TAC",
		"Type" => "tickbox",
		"Default" => false,
		"Required" => false,
	);

// .ORG.MY
$additionaldomainfields[".org.my"] = array();
$additionaldomainfields[".org.my"][] = array(
		"DisplayName" => "Trustee service (extra fee could be charged)",
		"Name" => "ACCEPT-TRUSTEE-TAC",
		"InwxName" => "ACCEPT-TRUSTEE-TAC",
		"Type" => "tickbox",
		"Default" => false,
		"Required" => false,
	);

// .NAME.MY
$additionaldomainfields[".name.my"] = array();
$additionaldomainfields[".name.my"][] = array(
		"DisplayName" => "Trustee service (extra fee could be charged)",
		"Name" => "ACCEPT-TRUSTEE-TAC",
		"InwxName" => "ACCEPT-TRUSTEE-TAC",
		"Type" => "tickbox",
		"Default" => false,
		"Required" => false,
	);

// .COM.GE
$additionaldomainfields[".com.ge"] = array();
$additionaldomainfields[".com.ge"][] = array(
		"DisplayName" => "Trustee service (extra fee could be charged)",
		"Name" => "ACCEPT-TRUSTEE-TAC",
		"InwxName" => "ACCEPT-TRUSTEE-TAC",
		"Type" => "tickbox",
		"Default" => false,
		"Required" => false,
	);

// .CO.ID
$additionaldomainfields[".co.id"] = array();
$additionaldomainfields[".co.id"][] = array(
		"DisplayName" => "Trustee service (extra fee could be charged)",
		"Name" => "ACCEPT-TRUSTEE-TAC",
		"InwxName" => "ACCEPT-TRUSTEE-TAC",
		"Type" => "tickbox",
		"Default" => false,
		"Required" => false,
	);

// .PM
$additionaldomainfields[".pm"] = array();
$additionaldomainfields[".pm"][] = array(
		"DisplayName" => "Trustee service (extra fee could be charged)",
		"Name" => "ACCEPT-TRUSTEE-TAC",
		"InwxName" => "ACCEPT-TRUSTEE-TAC",
		"Type" => "tickbox",
		"Default" => false,
		"Required" => false,
	);

// .TF
$additionaldomainfields[".tf"] = array();
$additionaldomainfields[".tf"][] = array(
		"DisplayName" => "Trustee service (extra fee could be charged)",
		"Name" => "ACCEPT-TRUSTEE-TAC",
		"InwxName" => "ACCEPT-TRUSTEE-TAC",
		"Type" => "tickbox",
		"Default" => false,
		"Required" => false,
	);

// .WF
$additionaldomainfields[".wf"] = array();
$additionaldomainfields[".wf"][] = array(
		"DisplayName" => "Trustee service (extra fee could be charged)",
		"Name" => "ACCEPT-TRUSTEE-TAC",
		"InwxName" => "ACCEPT-TRUSTEE-TAC",
		"Type" => "tickbox",
		"Default" => false,
		"Required" => false,
	);

// .YT
$additionaldomainfields[".yt"] = array();
$additionaldomainfields[".yt"][] = array(
		"DisplayName" => "Trustee service (extra fee could be charged)",
		"Name" => "ACCEPT-TRUSTEE-TAC",
		"InwxName" => "ACCEPT-TRUSTEE-TAC",
		"Type" => "tickbox",
		"Default" => false,
		"Required" => false,
	);

// .XN--90A3AC
$additionaldomainfields[".xn--90a3ac"] = array();
$additionaldomainfields[".xn--90a3ac"][] = array(
		"DisplayName" => "Trustee service (extra fee could be charged)",
		"Name" => "ACCEPT-TRUSTEE-TAC",
		"InwxName" => "ACCEPT-TRUSTEE-TAC",
		"Type" => "tickbox",
		"Default" => false,
		"Required" => false,
	);

// .SA
$additionaldomainfields[".sa"] = array();
$additionaldomainfields[".sa"][] = array(
		"DisplayName" => "Trustee service (extra fee could be charged)",
		"Name" => "ACCEPT-TRUSTEE-TAC",
		"InwxName" => "ACCEPT-TRUSTEE-TAC",
		"Type" => "tickbox",
		"Default" => false,
		"Required" => false,
	);

// .COM.SA
$additionaldomainfields[".com.sa"] = array();
$additionaldomainfields[".com.sa"][] = array(
		"DisplayName" => "Trustee service (extra fee could be charged)",
		"Name" => "ACCEPT-TRUSTEE-TAC",
		"InwxName" => "ACCEPT-TRUSTEE-TAC",
		"Type" => "tickbox",
		"Default" => false,
		"Required" => false,
	);

// .2000.HU
$additionaldomainfields[".2000.hu"] = array();
$additionaldomainfields[".2000.hu"][] = array(
		"DisplayName" => "Trustee service (extra fee could be charged)",
		"Name" => "ACCEPT-TRUSTEE-TAC",
		"InwxName" => "ACCEPT-TRUSTEE-TAC",
		"Type" => "tickbox",
		"Default" => false,
		"Required" => false,
	);

// .AGRAR.HU
$additionaldomainfields[".agrar.hu"] = array();
$additionaldomainfields[".agrar.hu"][] = array(
		"DisplayName" => "Trustee service (extra fee could be charged)",
		"Name" => "ACCEPT-TRUSTEE-TAC",
		"InwxName" => "ACCEPT-TRUSTEE-TAC",
		"Type" => "tickbox",
		"Default" => false,
		"Required" => false,
	);

// .BOLT.HU
$additionaldomainfields[".bolt.hu"] = array();
$additionaldomainfields[".bolt.hu"][] = array(
		"DisplayName" => "Trustee service (extra fee could be charged)",
		"Name" => "ACCEPT-TRUSTEE-TAC",
		"InwxName" => "ACCEPT-TRUSTEE-TAC",
		"Type" => "tickbox",
		"Default" => false,
		"Required" => false,
	);

// .CASINO.HU
$additionaldomainfields[".casino.hu"] = array();
$additionaldomainfields[".casino.hu"][] = array(
		"DisplayName" => "Trustee service (extra fee could be charged)",
		"Name" => "ACCEPT-TRUSTEE-TAC",
		"InwxName" => "ACCEPT-TRUSTEE-TAC",
		"Type" => "tickbox",
		"Default" => false,
		"Required" => false,
	);

// .CITY.HU
$additionaldomainfields[".city.hu"] = array();
$additionaldomainfields[".city.hu"][] = array(
		"DisplayName" => "Trustee service (extra fee could be charged)",
		"Name" => "ACCEPT-TRUSTEE-TAC",
		"InwxName" => "ACCEPT-TRUSTEE-TAC",
		"Type" => "tickbox",
		"Default" => false,
		"Required" => false,
	);

// .EROTICA.HU
$additionaldomainfields[".erotica.hu"] = array();
$additionaldomainfields[".erotica.hu"][] = array(
		"DisplayName" => "Trustee service (extra fee could be charged)",
		"Name" => "ACCEPT-TRUSTEE-TAC",
		"InwxName" => "ACCEPT-TRUSTEE-TAC",
		"Type" => "tickbox",
		"Default" => false,
		"Required" => false,
	);

// .EROTIKA.HU
$additionaldomainfields[".erotika.hu"] = array();
$additionaldomainfields[".erotika.hu"][] = array(
		"DisplayName" => "Trustee service (extra fee could be charged)",
		"Name" => "ACCEPT-TRUSTEE-TAC",
		"InwxName" => "ACCEPT-TRUSTEE-TAC",
		"Type" => "tickbox",
		"Default" => false,
		"Required" => false,
	);

// .FILM.HU
$additionaldomainfields[".film.hu"] = array();
$additionaldomainfields[".film.hu"][] = array(
		"DisplayName" => "Trustee service (extra fee could be charged)",
		"Name" => "ACCEPT-TRUSTEE-TAC",
		"InwxName" => "ACCEPT-TRUSTEE-TAC",
		"Type" => "tickbox",
		"Default" => false,
		"Required" => false,
	);

// .FORUM.HU
$additionaldomainfields[".forum.hu"] = array();
$additionaldomainfields[".forum.hu"][] = array(
		"DisplayName" => "Trustee service (extra fee could be charged)",
		"Name" => "ACCEPT-TRUSTEE-TAC",
		"InwxName" => "ACCEPT-TRUSTEE-TAC",
		"Type" => "tickbox",
		"Default" => false,
		"Required" => false,
	);

// .GAMES.HU
$additionaldomainfields[".games.hu"] = array();
$additionaldomainfields[".games.hu"][] = array(
		"DisplayName" => "Trustee service (extra fee could be charged)",
		"Name" => "ACCEPT-TRUSTEE-TAC",
		"InwxName" => "ACCEPT-TRUSTEE-TAC",
		"Type" => "tickbox",
		"Default" => false,
		"Required" => false,
	);

// .HOTEL.HU
$additionaldomainfields[".hotel.hu"] = array();
$additionaldomainfields[".hotel.hu"][] = array(
		"DisplayName" => "Trustee service (extra fee could be charged)",
		"Name" => "ACCEPT-TRUSTEE-TAC",
		"InwxName" => "ACCEPT-TRUSTEE-TAC",
		"Type" => "tickbox",
		"Default" => false,
		"Required" => false,
	);

// .INFO.HU
$additionaldomainfields[".info.hu"] = array();
$additionaldomainfields[".info.hu"][] = array(
		"DisplayName" => "Trustee service (extra fee could be charged)",
		"Name" => "ACCEPT-TRUSTEE-TAC",
		"InwxName" => "ACCEPT-TRUSTEE-TAC",
		"Type" => "tickbox",
		"Default" => false,
		"Required" => false,
	);

// .INGATLAN.HU
$additionaldomainfields[".ingatlan.hu"] = array();
$additionaldomainfields[".ingatlan.hu"][] = array(
		"DisplayName" => "Trustee service (extra fee could be charged)",
		"Name" => "ACCEPT-TRUSTEE-TAC",
		"InwxName" => "ACCEPT-TRUSTEE-TAC",
		"Type" => "tickbox",
		"Default" => false,
		"Required" => false,
	);

// .JOGASZ.HU
$additionaldomainfields[".jogasz.hu"] = array();
$additionaldomainfields[".jogasz.hu"][] = array(
		"DisplayName" => "Trustee service (extra fee could be charged)",
		"Name" => "ACCEPT-TRUSTEE-TAC",
		"InwxName" => "ACCEPT-TRUSTEE-TAC",
		"Type" => "tickbox",
		"Default" => false,
		"Required" => false,
	);

// .KONYVELO.HU
$additionaldomainfields[".konyvelo.hu"] = array();
$additionaldomainfields[".konyvelo.hu"][] = array(
		"DisplayName" => "Trustee service (extra fee could be charged)",
		"Name" => "ACCEPT-TRUSTEE-TAC",
		"InwxName" => "ACCEPT-TRUSTEE-TAC",
		"Type" => "tickbox",
		"Default" => false,
		"Required" => false,
	);

// .LAKAS.HU
$additionaldomainfields[".lakas.hu"] = array();
$additionaldomainfields[".lakas.hu"][] = array(
		"DisplayName" => "Trustee service (extra fee could be charged)",
		"Name" => "ACCEPT-TRUSTEE-TAC",
		"InwxName" => "ACCEPT-TRUSTEE-TAC",
		"Type" => "tickbox",
		"Default" => false,
		"Required" => false,
	);

// .MEDIA.HU
$additionaldomainfields[".media.hu"] = array();
$additionaldomainfields[".media.hu"][] = array(
		"DisplayName" => "Trustee service (extra fee could be charged)",
		"Name" => "ACCEPT-TRUSTEE-TAC",
		"InwxName" => "ACCEPT-TRUSTEE-TAC",
		"Type" => "tickbox",
		"Default" => false,
		"Required" => false,
	);

// .NEWS.HU
$additionaldomainfields[".news.hu"] = array();
$additionaldomainfields[".news.hu"][] = array(
		"DisplayName" => "Trustee service (extra fee could be charged)",
		"Name" => "ACCEPT-TRUSTEE-TAC",
		"InwxName" => "ACCEPT-TRUSTEE-TAC",
		"Type" => "tickbox",
		"Default" => false,
		"Required" => false,
	);

// .ORG.HU
$additionaldomainfields[".org.hu"] = array();
$additionaldomainfields[".org.hu"][] = array(
		"DisplayName" => "Trustee service (extra fee could be charged)",
		"Name" => "ACCEPT-TRUSTEE-TAC",
		"InwxName" => "ACCEPT-TRUSTEE-TAC",
		"Type" => "tickbox",
		"Default" => false,
		"Required" => false,
	);

// .PRIV.HU
$additionaldomainfields[".priv.hu"] = array();
$additionaldomainfields[".priv.hu"][] = array(
		"DisplayName" => "Trustee service (extra fee could be charged)",
		"Name" => "ACCEPT-TRUSTEE-TAC",
		"InwxName" => "ACCEPT-TRUSTEE-TAC",
		"Type" => "tickbox",
		"Default" => false,
		"Required" => false,
	);

// .REKLAM.HU
$additionaldomainfields[".reklam.hu"] = array();
$additionaldomainfields[".reklam.hu"][] = array(
		"DisplayName" => "Trustee service (extra fee could be charged)",
		"Name" => "ACCEPT-TRUSTEE-TAC",
		"InwxName" => "ACCEPT-TRUSTEE-TAC",
		"Type" => "tickbox",
		"Default" => false,
		"Required" => false,
	);

// .SEX.HU
$additionaldomainfields[".sex.hu"] = array();
$additionaldomainfields[".sex.hu"][] = array(
		"DisplayName" => "Trustee service (extra fee could be charged)",
		"Name" => "ACCEPT-TRUSTEE-TAC",
		"InwxName" => "ACCEPT-TRUSTEE-TAC",
		"Type" => "tickbox",
		"Default" => false,
		"Required" => false,
	);

// .SHOP.HU
$additionaldomainfields[".shop.hu"] = array();
$additionaldomainfields[".shop.hu"][] = array(
		"DisplayName" => "Trustee service (extra fee could be charged)",
		"Name" => "ACCEPT-TRUSTEE-TAC",
		"InwxName" => "ACCEPT-TRUSTEE-TAC",
		"Type" => "tickbox",
		"Default" => false,
		"Required" => false,
	);

// .SPORT.HU
$additionaldomainfields[".sport.hu"] = array();
$additionaldomainfields[".sport.hu"][] = array(
		"DisplayName" => "Trustee service (extra fee could be charged)",
		"Name" => "ACCEPT-TRUSTEE-TAC",
		"InwxName" => "ACCEPT-TRUSTEE-TAC",
		"Type" => "tickbox",
		"Default" => false,
		"Required" => false,
	);

// .SULI.HU
$additionaldomainfields[".suli.hu"] = array();
$additionaldomainfields[".suli.hu"][] = array(
		"DisplayName" => "Trustee service (extra fee could be charged)",
		"Name" => "ACCEPT-TRUSTEE-TAC",
		"InwxName" => "ACCEPT-TRUSTEE-TAC",
		"Type" => "tickbox",
		"Default" => false,
		"Required" => false,
	);

// .SZEX.HU
$additionaldomainfields[".szex.hu"] = array();
$additionaldomainfields[".szex.hu"][] = array(
		"DisplayName" => "Trustee service (extra fee could be charged)",
		"Name" => "ACCEPT-TRUSTEE-TAC",
		"InwxName" => "ACCEPT-TRUSTEE-TAC",
		"Type" => "tickbox",
		"Default" => false,
		"Required" => false,
	);

// .TM.HU
$additionaldomainfields[".tm.hu"] = array();
$additionaldomainfields[".tm.hu"][] = array(
		"DisplayName" => "Trustee service (extra fee could be charged)",
		"Name" => "ACCEPT-TRUSTEE-TAC",
		"InwxName" => "ACCEPT-TRUSTEE-TAC",
		"Type" => "tickbox",
		"Default" => false,
		"Required" => false,
	);

// .TOZSDE.HU
$additionaldomainfields[".tozsde.hu"] = array();
$additionaldomainfields[".tozsde.hu"][] = array(
		"DisplayName" => "Trustee service (extra fee could be charged)",
		"Name" => "ACCEPT-TRUSTEE-TAC",
		"InwxName" => "ACCEPT-TRUSTEE-TAC",
		"Type" => "tickbox",
		"Default" => false,
		"Required" => false,
	);

// .UTAZAS.HU
$additionaldomainfields[".utazas.hu"] = array();
$additionaldomainfields[".utazas.hu"][] = array(
		"DisplayName" => "Trustee service (extra fee could be charged)",
		"Name" => "ACCEPT-TRUSTEE-TAC",
		"InwxName" => "ACCEPT-TRUSTEE-TAC",
		"Type" => "tickbox",
		"Default" => false,
		"Required" => false,
	);

// .VIDEO.HU
$additionaldomainfields[".video.hu"] = array();
$additionaldomainfields[".video.hu"][] = array(
		"DisplayName" => "Trustee service (extra fee could be charged)",
		"Name" => "ACCEPT-TRUSTEE-TAC",
		"InwxName" => "ACCEPT-TRUSTEE-TAC",
		"Type" => "tickbox",
		"Default" => false,
		"Required" => false,
	);

// .TN
$additionaldomainfields[".tn"] = array();
$additionaldomainfields[".tn"][] = array(
		"DisplayName" => "Trustee service (extra fee could be charged)",
		"Name" => "ACCEPT-TRUSTEE-TAC",
		"InwxName" => "ACCEPT-TRUSTEE-TAC",
		"Type" => "tickbox",
		"Default" => false,
		"Required" => false,
	);

// .COM.TN
$additionaldomainfields[".com.tn"] = array();
$additionaldomainfields[".com.tn"][] = array(
		"DisplayName" => "Trustee service (extra fee could be charged)",
		"Name" => "ACCEPT-TRUSTEE-TAC",
		"InwxName" => "ACCEPT-TRUSTEE-TAC",
		"Type" => "tickbox",
		"Default" => false,
		"Required" => false,
	);

// .CO.TZ
$additionaldomainfields[".co.tz"] = array();
$additionaldomainfields[".co.tz"][] = array(
		"DisplayName" => "Trustee service (extra fee could be charged)",
		"Name" => "ACCEPT-TRUSTEE-TAC",
		"InwxName" => "ACCEPT-TRUSTEE-TAC",
		"Type" => "tickbox",
		"Default" => false,
		"Required" => false,
	);

// .COM.KW
$additionaldomainfields[".com.kw"] = array();
$additionaldomainfields[".com.kw"][] = array(
		"DisplayName" => "Trustee service (extra fee could be charged)",
		"Name" => "ACCEPT-TRUSTEE-TAC",
		"InwxName" => "ACCEPT-TRUSTEE-TAC",
		"Type" => "tickbox",
		"Default" => false,
		"Required" => false,
	);

// .COM.LB
$additionaldomainfields[".com.lb"] = array();
$additionaldomainfields[".com.lb"][] = array(
		"DisplayName" => "Trustee service (extra fee could be charged)",
		"Name" => "ACCEPT-TRUSTEE-TAC",
		"InwxName" => "ACCEPT-TRUSTEE-TAC",
		"Type" => "tickbox",
		"Default" => false,
		"Required" => false,
	);

// .BAYERN
$additionaldomainfields[".bayern"] = array();
$additionaldomainfields[".bayern"][] = array(
		"DisplayName" => "Trustee service (extra fee could be charged)",
		"Name" => "ACCEPT-TRUSTEE-TAC",
		"InwxName" => "ACCEPT-TRUSTEE-TAC",
		"Type" => "tickbox",
		"Default" => false,
		"Required" => false,
	);

// .UK
$additionaldomainfields[".uk"] = array();
$additionaldomainfields[".uk"][] = array(
		"DisplayName" => "Trustee service (extra fee could be charged)",
		"Name" => "ACCEPT-TRUSTEE-TAC",
		"InwxName" => "ACCEPT-TRUSTEE-TAC",
		"Type" => "tickbox",
		"Default" => false,
		"Required" => false,
	);

// .OR.KR
$additionaldomainfields[".or.kr"] = array();
$additionaldomainfields[".or.kr"][] = array(
		"DisplayName" => "Trustee service (extra fee could be charged)",
		"Name" => "ACCEPT-TRUSTEE-TAC",
		"InwxName" => "ACCEPT-TRUSTEE-TAC",
		"Type" => "tickbox",
		"Default" => false,
		"Required" => false,
	);

// .BIZ.ID
$additionaldomainfields[".biz.id"] = array();
$additionaldomainfields[".biz.id"][] = array(
		"DisplayName" => "Trustee service (extra fee could be charged)",
		"Name" => "ACCEPT-TRUSTEE-TAC",
		"InwxName" => "ACCEPT-TRUSTEE-TAC",
		"Type" => "tickbox",
		"Default" => false,
		"Required" => false,
	);

// .WEB.ID
$additionaldomainfields[".web.id"] = array();
$additionaldomainfields[".web.id"][] = array(
		"DisplayName" => "Trustee service (extra fee could be charged)",
		"Name" => "ACCEPT-TRUSTEE-TAC",
		"InwxName" => "ACCEPT-TRUSTEE-TAC",
		"Type" => "tickbox",
		"Default" => false,
		"Required" => false,
	);

// .MY.ID
$additionaldomainfields[".my.id"] = array();
$additionaldomainfields[".my.id"][] = array(
		"DisplayName" => "Trustee service (extra fee could be charged)",
		"Name" => "ACCEPT-TRUSTEE-TAC",
		"InwxName" => "ACCEPT-TRUSTEE-TAC",
		"Type" => "tickbox",
		"Default" => false,
		"Required" => false,
	);

// .ID
$additionaldomainfields[".id"] = array();
$additionaldomainfields[".id"][] = array(
		"DisplayName" => "Trustee service (extra fee could be charged)",
		"Name" => "ACCEPT-TRUSTEE-TAC",
		"InwxName" => "ACCEPT-TRUSTEE-TAC",
		"Type" => "tickbox",
		"Default" => false,
		"Required" => false,
	);


?>