<?php

/*
 * generated by INWX on 2025-08-11T10:21:37+02:00
 *
 */
$_ADDONLANG['inwx_RegistrantsBirthdate'] = 'Geburtsdatum des Inhabers';
$_ADDONLANG['inwx_RegistrantsBirthplace'] = 'Geburtsort des Inhabers';
$_ADDONLANG['inwx_TrademarkName'] = 'Markenname';
$_ADDONLANG['inwx_TrademarkNumber'] = 'Markennummer';
$_ADDONLANG['inwx_CompanyNo'] = 'Firmennummer';
$_ADDONLANG['inwx_VatNo'] = 'USt.-ID-Nr.';
$_ADDONLANG['inwx_IDcardNo'] = 'Personalausweisnr.';
$_ADDONLANG['inwx_IDcardIssuerDate'] = 'Personalausweis-Ausstelldatum';
$_ADDONLANG['inwx_SkLegalForm'] = '.SK Inhaberart';
$_ADDONLANG['inwx_UsAppPurpose'] = '.US Domainnutzung';
$_ADDONLANG['inwx_UsNexusCategory'] = '.US Inhaberart';
$_ADDONLANG['inwx_AEImportantNotice'] = '.AE Wichtiger Hinweis';
$_ADDONLANG['inwx_NameEmailForward'] = '.NAME E-Mail Weiterleitung';
$_ADDONLANG['inwx_NicSeIdNumber'] = '.SE ID Nummer';
$_ADDONLANG['inwx_IDcardIssuer'] = 'Personalausweis-Aussteller';
$_ADDONLANG['inwx_CaLegalType'] = '.CA Inhaberart';
$_ADDONLANG['inwx_ItCodiceFiscale'] = '.IT codice fiscale';
$_ADDONLANG['inwx_FiHenkilotunnus'] = 'Henkilötunnus';
$_ADDONLANG['inwx_TaxNumber'] = 'Steuernummer';
$_ADDONLANG['inwx_AeroEnsAuthId'] = '.AERO ID';
$_ADDONLANG['inwx_AeroEnsAuthKey'] = '.AERO KEY';
$_ADDONLANG['inwx_DunsNumber'] = 'DUNS-Nummer';
$_ADDONLANG['inwx_EeaLocalId'] = 'Lokale ID innerhalb des EWR';
$_ADDONLANG['inwx_AuDomainIdType'] = '.AU Identifikationsart';
$_ADDONLANG['inwx_AuDomainRelation'] = '.AU Domainbeziehung';
$_ADDONLANG['inwx_AuDomainRelationType'] = '.AU Inhaberform';
$_ADDONLANG['inwx_KrCtfyType'] = '.KR Certify Typ';
$_ADDONLANG['inwx_KrCtfyNo'] = '.KR Certify Nummer';
$_ADDONLANG['inwx_AdminBirthDate'] = 'Geburtsdatum des administrativen Kontakts';
$_ADDONLANG['inwx_AdminIdcardOrPassportNumber'] = 'Personalausweisnr. des administrativen Kontakts';
$_ADDONLANG['inwx_TechBirthDate'] = 'Geburtsdatum des technischen Kontakts';
$_ADDONLANG['inwx_TechIdcardOrPassportNumber'] = 'Personalausweisnr. des technischen Kontakts';
$_ADDONLANG['inwx_OwnerContactNameIsLegalRepresentative'] = 'Ich bestätige, dass der Name des Domaininhaberkontakts ein rechtlicher Vertreter der Firma ist, wie er im Handelsregisterauszug aufgeführt ist.';
$_ADDONLANG['inwx_BgRegistrationTacApproved'] = 'Ich bestätige, die rechtzeitige postalische Einsendung der angeforderten Dokumente innerhalb 30 Tagen nach Zustellung vorzunehmen. Es gilt der Eingang der Unterlagen beim Empfänger. Die Dokumente erhalte ich nach Benachrichtigung in der Regel innerhalb eines Werktages nach Einleiten des Registrierungsauftrages als Download über die Domainliste.';
$_ADDONLANG['inwx_CnIcpNumber'] = '.CN ICP-Nummer';
$_ADDONLANG['inwx_CnRegistrationTacApproved'] = 'Hiermit nehme ich zur Kenntnis, dass authentische, korrekte und vollständige Dokumente für die Registrierung einzureichen sind. Dies sind eine Kopie eines offiziellen Dokuments zur Feststellung der Identität des Domaininhabers (Personalausweis, Pass, Führerschein, etc.) bei natürlichen Personen beziehungsweise eine Kopie eines Dokuments welches die Firmeneintragung belegt (Handelsregisterauszug etc.) bei Firmen.
Die Registrierungsbedingungen und Richtlinien der Registrierungsstelle CNNIC habe ich gelesen und verstanden. Die Richtlinien zur Regelung der Inhalte von Webseiten unter dem Domainnamen sind einzuhalten.
Bei Nutzung der Domain für einen Webserver auf dem Gebiet der Volksrepublik China ist eine von der MIIT vergebene gültige ICP-Nummer des Inhabers vorzuweisen.
Für eine Sperrung der Domain oder etwaige Konsequenzen infolge von Verstößen gegen die eingegangenen Verpflichtungen bin ich selbst verantwortlich und mir ist bewusst, dass die Registrierungsstelle und der Registrar keine Verantwortung im Falle einer Sperrung der Domain übernehmen.';
$_ADDONLANG['inwx_BgApplicationNumber'] = '.BG Applikationsnummer';
$_ADDONLANG['inwx_IrNationalId'] = 'Iranische Nationale ID';
$_ADDONLANG['inwx_IrOrganizationId'] = 'Iranische Organisations-ID';
$_ADDONLANG['inwx_IrCompanyRegistrationCenter'] = 'Firmeneintragungsbehörde';
$_ADDONLANG['inwx_IrCompanyRegistrationCc'] = 'Land der Firmeneintragungsbehörde';
$_ADDONLANG['inwx_IrCompanyRegistrationSp'] = 'Region/Provinz der Firmeneintragungsbehörde';
$_ADDONLANG['inwx_IrCompanyRegistrationType'] = '.IR Firmentyp';
$_ADDONLANG['inwx_BrCpf'] = 'CPF (brasilianische Steuernummer)';
$_ADDONLANG['inwx_BrCnpj'] = 'CNPJ (brasilianische Firmennummer)';
$_ADDONLANG['inwx_HrOib'] = 'OIB (kroatische Identifikationsnummer)';
$_ADDONLANG['inwx_TechTaxNumber'] = 'Steuernummer des technischen Kontakts';
$_ADDONLANG['inwx_TechVatNumber'] = 'USt.-ID-Nr. des technischen Kontakts';
$_ADDONLANG['inwx_IdcardCc'] = 'Ausstellungsland des Ausweises';
$_ADDONLANG['inwx_ES-NIF-NIE'] = 'Spanische Steuernummer (NIF/NIE)';
$_ADDONLANG['inwx_ES-ADMIN-NIF-NIE'] = 'Spanische Steuernummer Admin Kontakts (NIF/NIE)';
$_ADDONLANG['inwx_ES-LEGAL-FORM'] = '.ES Rechtsform des Inhabers';
$_ADDONLANG['inwx_ES-ID-TYPE'] = '.ES Identifikationsart des Inhabers';
$_ADDONLANG['inwx_ES-ADMIN-ID-TYPE'] = '.ES Identifikationsart des administrativen Kontakts';
$_ADDONLANG['inwx_NO-PERSON-IDENTIFIER'] = '.NO Person Identifier (PID)';
$_ADDONLANG['inwx_IS-KENNITALA'] = 'Isländische Identifikationsnummer (Kennitala)';
$_ADDONLANG['inwx_SG-ADMIN-SINGPASSID'] = 'Singapore Personal Access ID des administrativen Kontakts';
$_ADDONLANG['inwx_TAX-OFFICE'] = 'Steuerbehörde';
$_ADDONLANG['inwx_ACKNOWLEDGE-SECURE-ONLY-APP'] = 'Mir ist bekannt, dass meine neue .APP-Domain durch die Voraktivierung von HSTS besonders sicher ist und ich meine Webseite mit einem SSL Zertifikat betreiben muss um diese Domain verwenden zu können. Ich wurde von INWX informiert, wie ich ein SSL Zertifikat bestellen kann, um meine .APP-Domain zu nutzen.';
$_ADDONLANG['inwx_ACKNOWLEDGE-SECURE-ONLY-PAGE'] = 'Mir ist bekannt, dass meine neue .PAGE-Domain durch die Voraktivierung von HSTS besonders sicher ist, und ich meine Webseite mit einem SSL Zertifikat betreiben muss um diese Domain verwenden zu können. Ich wurde von INWX informiert, wie ich ein SSL Zertifikat bestellen kann, um meine .PAGE-Domain zu nutzen.';
$_ADDONLANG['inwx_TRAVEL-IN-INDUSTRY'] = '.travel-Domains können nur von Firmen, Organisationen und Personen registriert werden, die in der Reisebranche tätig sind oder Tätigkeiten in der Reisebranche planen. Mit der Anmeldung versichern Sie, diese Voraussetzung zu erfüllen. Ein Nachweis kann zu einem späteren Zeitpunkt von der Vergabestelle verlangt werden. Wird der Nachweis nicht erbracht, kann die Domain suspendiert werden.';
$_ADDONLANG['inwx_ACKNOWLEDGE-SECURE-ONLY-DEV'] = 'Mir ist bekannt, dass meine neue .DEV-Domain durch die Voraktivierung von HSTS besonders sicher ist und ich meine Webseite mit einem SSL Zertifikat betreiben muss um diese Domain verwenden zu können. Ich wurde von INWX informiert, wie ich ein SSL Zertifikat bestellen kann, um meine .DEV-Domain zu nutzen.';
$_ADDONLANG['inwx_LEGAL-REPRESENTATIVE'] = 'Gesetzlicher Vertreter';
$_ADDONLANG['inwx_INTENDED-USE'] = 'Verwendungszweck';
$_ADDONLANG['inwx_ACKNOWLEDGE-SECURE-ONLY-NEW'] = 'Mir ist bekannt, dass meine neue .NEW-Domain durch die Voraktivierung von HSTS besonders sicher ist und ich meine Webseite mit einem SSL Zertifikat betreiben muss um diese Domain verwenden zu können.
Ich wurde von INWX informiert, wie ich ein SSL Zertifikat bestellen kann, um meine .NEW-Domain zu nutzen.';
$_ADDONLANG['inwx_DOT-NEW-CONFIRMATION'] = '.NEW ist ausschließlich für die Durchführung neuer Aktionen bestimmt. Das Navigieren zu einer .NEW-Domain muss dem Benutzer erlauben, eine Aktion oder Online-Inhalte mit höchstens einem Klick zu erstellen. Andere Anwendungsfälle sind nicht zulässig. Mit der Registrierung einer .NEW-Domain erklären Sie sich damit einverstanden die .NEW-Registrierungsrichtlinie umzusetzen, einschließlich der Sicherstellung, dass Ihre Domain innerhalb von 100 Tagen nach dem Registrierungsdatum live und konform ist.
Registrierungen, die nicht der Registrierungsrichtlinie entsprechen, können ohne Rückerstattung gesperrt oder gelöscht werden. Bitte besuchen Sie https://www.registry.google/policies/registration/new/#!/ für die vollständige Richtlinie.';
$_ADDONLANG['inwx_GAY-ACCEPT-REQUIREMENTS'] = 'Ich akzeptiere die .gay Rights Protections Policy unter <a href=\'https://toplevel.design/policy\' target=\'_blank\'>https://toplevel.design/policy</a><br>
20% der Einnahmen aus der Neuregistrierung von .gay-Domains werden an gemeinnützige LGBTQ-Organisationen gespendet.';
$_ADDONLANG['inwx_COOP-ACCEPT-REQUIREMENTS'] = 'Ich stimme zu und bestätige, dass meine Organisation als Registrant mindestens eine der .COOP-Eignungsvoraussetzungen erfüllt:

- Die Organisation ist eine demokratisch kontrollierte, mitgliedergeführte Genossenschaft, in Übereinstimmung mit den Internationalen 7 Genossenschaftsprinzipien oder
- Die Organisation ist eine Vereinigung, die aus Genossenschaften besteht oder
- Die Organisation wird mehrheitlich von einer Genossenschaft kontrolliert wird oder
- Die Tätigkeit der Organisation steht hauptsächlich im Dienste von Genossenschaften.

Ich verstehe und stimme zu, dass DotCooperation LLC Prüfungen von .COOP-Domainregistrierungen durchführt und sich das Recht vorbehält, einen Domainnamen in Übereinstimmung mit ihren Richtlinien zu stornieren oder zu ändern.';
$_ADDONLANG['inwx_NGO-ACCEPT-REQUIREMENTS'] = 'Ich stimme den Registrierungsrichtlinien <a href=\'https://pir.org/our-impact/ngo-ong-policy/\' target=\'_blank\'> der .ngo & .ong Policy zu und bestätige, dass die als Domaininhaber angegebene Organisation die darin enthaltenen Zulassungsvoraussetzungen erfüllt.';
$_ADDONLANG['inwx_ACKNOWLEDGE-SECURE-ONLY-DAY'] = 'Mir ist bekannt, dass meine neue .DAY-Domain durch die Voraktivierung von HSTS besonders sicher ist und ich meine Webseite mit einem SSL Zertifikat betreiben muss um diese Domain verwenden zu können. Ich wurde von INWX informiert, wie ich ein SSL Zertifikat bestellen kann, um meine .DAY-Domain zu nutzen.';
$_ADDONLANG['inwx_ACKNOWLEDGE-SECURE-ONLY-BOO'] = 'Mir ist bekannt, dass meine neue .BOO-Domain durch die Voraktivierung von HSTS besonders sicher ist und ich meine Webseite mit einem SSL Zertifikat betreiben muss um diese Domain verwenden zu können. Ich wurde von INWX informiert, wie ich ein SSL Zertifikat bestellen kann, um meine .BOO-Domain zu nutzen.';
$_ADDONLANG['inwx_ACKNOWLEDGE-SECURE-ONLY-RSVP'] = 'Mir ist bekannt, dass meine neue .RSVP-Domain durch die Voraktivierung von HSTS besonders sicher ist und ich meine Webseite mit einem SSL Zertifikat betreiben muss um diese Domain verwenden zu können. Ich wurde von INWX informiert, wie ich ein SSL Zertifikat bestellen kann, um meine .RSVP-Domain zu nutzen.';
$_ADDONLANG['inwx_DK-ACCEPT-REGISTRAR'] = '<b>Verwaltung durch Registrar akzeptieren</b><br/><br/>
Ich akzeptiere, dass INWX meine .dk-Domain verwaltet. Sie stimmen zu, dass Sie INWX das Recht einräumen, Zahlungen an DK Hostmaster zu leisten, Nameserver und Kontaktinformationen zu ändern oder den Domainnamen in Ihrem Namen zu kündigen.
Sie können dies jederzeit im Self-Service von Dk Hostmaster ändern. Weitere Informationen finden Sie <a href=\"https://www.dk-hostmaster.dk/en/who-dk-hostmaster\" target=\"_blank\">hier</a>';
$_ADDONLANG['inwx_ACKNOWLEDGE-SECURE-ONLY-MOV'] = 'Mir ist bekannt, dass meine neue .MOV-Domain durch die Voraktivierung von HSTS besonders sicher ist und ich meine Webseite mit einem SSL Zertifikat betreiben muss um diese Domain verwenden zu können. Ich wurde von INWX informiert, wie ich ein SSL Zertifikat bestellen kann, um meine .MOV-Domain zu nutzen.';
$_ADDONLANG['inwx_ACKNOWLEDGE-SECURE-ONLY-PHD'] = 'Mir ist bekannt, dass meine neue .PHD-Domain durch die Voraktivierung von HSTS besonders sicher ist und ich meine Webseite mit einem SSL Zertifikat betreiben muss um diese Domain verwenden zu können. Ich wurde von INWX informiert, wie ich ein SSL Zertifikat bestellen kann, um meine .PHD-Domain zu nutzen.';
$_ADDONLANG['inwx_ACKNOWLEDGE-SECURE-ONLY-PROF'] = 'Mir ist bekannt, dass meine neue .PROF-Domain durch die Voraktivierung von HSTS besonders sicher ist und ich meine Webseite mit einem SSL Zertifikat betreiben muss um diese Domain verwenden zu können. Ich wurde von INWX informiert, wie ich ein SSL Zertifikat bestellen kann, um meine .PROF-Domain zu nutzen.';
$_ADDONLANG['inwx_ACKNOWLEDGE-SECURE-ONLY-ESQ'] = 'Mir ist bekannt, dass meine neue .ESQ-Domain durch die Voraktivierung von HSTS besonders sicher ist und ich meine Webseite mit einem SSL Zertifikat betreiben muss um diese Domain verwenden zu können. Ich wurde von INWX informiert, wie ich ein SSL Zertifikat bestellen kann, um meine .ESQ-Domain zu nutzen.';
$_ADDONLANG['inwx_ACKNOWLEDGE-SECURE-ONLY-NEXUS'] = 'Mir ist bekannt, dass meine neue .NEXUS-Domain durch die Voraktivierung von HSTS besonders sicher ist und ich meine Webseite mit einem SSL Zertifikat betreiben muss um diese Domain verwenden zu können. Ich wurde von INWX informiert, wie ich ein SSL Zertifikat bestellen kann, um meine .NEXUS-Domain zu nutzen.';
$_ADDONLANG['inwx_ACKNOWLEDGE-SECURE-ONLY-DAD'] = 'Mir ist bekannt, dass meine neue .DAD-Domain durch die Voraktivierung von HSTS besonders sicher ist und ich meine Webseite mit einem SSL Zertifikat betreiben muss um diese Domain verwenden zu können. Ich wurde von INWX informiert, wie ich ein SSL Zertifikat bestellen kann, um meine .DAD-Domain zu nutzen.';
$_ADDONLANG['inwx_ACKNOWLEDGE-SECURE-ONLY-FOO'] = 'Mir ist bekannt, dass meine neue .FOO-Domain durch die Voraktivierung von HSTS besonders sicher ist und ich meine Webseite mit einem SSL Zertifikat betreiben muss um diese Domain verwenden zu können. Ich wurde von INWX informiert, wie ich ein SSL Zertifikat bestellen kann, um meine .FOO-Domain zu nutzen.';
$_ADDONLANG['inwx_ACKNOWLEDGE-SECURE-ONLY-ZIP'] = 'Mir ist bekannt, dass meine neue .ZIP-Domain durch die Voraktivierung von HSTS besonders sicher ist und ich meine Webseite mit einem SSL Zertifikat betreiben muss um diese Domain verwenden zu können. Ich wurde von INWX informiert, wie ich ein SSL Zertifikat bestellen kann, um meine .ZIP-Domain zu nutzen.';
$_ADDONLANG['inwx_HK-INDUSTRY-TYPE'] = 'Branche';
$_ADDONLANG['inwx_ACKNOWLEDGE-SECURE-ONLY-MEME'] = 'Mir ist bekannt, dass meine neue .MEME-Domain durch die Voraktivierung von HSTS besonders sicher ist und ich meine Webseite mit einem SSL Zertifikat betreiben muss um diese Domain verwenden zu können. Ich wurde von INWX informiert, wie ich ein SSL Zertifikat bestellen kann, um meine .MEME-Domain zu nutzen.';
$_ADDONLANG['inwx_ACKNOWLEDGE-SECURE-ONLY-ING'] = 'Mir ist bekannt, dass meine neue .ING-Domain durch die Voraktivierung von HSTS besonders sicher ist und ich meine Webseite mit einem SSL Zertifikat betreiben muss um diese Domain verwenden zu können. Ich wurde von INWX informiert, wie ich ein SSL Zertifikat bestellen kann, um meine .ING-Domain zu nutzen.';
$_ADDONLANG['inwx_MUSIC-ACCEPT-REQUIREMENTS'] = '<strong>.MUSIC-Domain-Registrierungsanforderungen</strong>
<ul>
<li><strong>Identitätsüberprüfung (KYC/KYB):</strong> Sie müssen nach der Registrierung einen obligatorischen Identitätsverifizierungsprozess (Know Your Customer/Know Your Business) abschließen. Ihre Domain bleibt inaktiv, bis dieser Prozess erfolgreich abgeschlossen ist. Dies muss unter id.music erfolgen.</li>
<li><strong>Musik-Community-Verbindung (Nexus-Anforderung):</strong> Sie <strong>müssen eine nachweisbare Verbindung zu dem spezifischen Domainnamen (String)</strong> haben, den Sie registrieren möchten. Diese Verbindung kann historisch, kommerziell oder beruflich sein, und <strong>Sie können keine .MUSIC-Domain registrieren, ohne eine legitime Verbindung zu dem Namen nachzuweisen</strong>. Die Registrierungstelle wird Ihre Behauptung überprüfen, und das Versäumnis, diesen Nachweis zu erbringen, kann zur Sperrung oder zum Verlust Ihrer Domain ohne Rückerstattung führen.</li>
</ul>
<strong>Indem Sie mit dem Kauf fortfahren, erkennen Sie diese Anforderungen an und stimmen ihnen zu.</strong>';
$_ADDONLANG['inwx_GM-ACCEPT-REQUIREMENTS'] = 'Ich habe die Regeln und Richtlinien für die Registrierung von .GM Domains gelesen und verstanden, einschließlich:

Der Inhaber einer .GM-Domain muss eine Person oder Organisation sein, die entweder in Gambia ansässig ist, Informationen oder Dienstleistungen für Gambia oder über Gambia anbietet oder deren Arbeit anderweitig der \"lokalen Internetgemeinschaft\" in Gambia zugute kommt.

Eine Organisation, die ihren Namen schützen möchte, kann eine Domain registrieren, wenn diese klar und eindeutig die registrierende Organisation identifiziert. Die Gültigkeit der Verbindung wird von der Registrierungsstelle überprüft.';
$_ADDONLANG['inwx_BANK-ACCEPT-REQUIREMENTS'] = 'Um eine .bank-Domain zu registrieren, müssen Sie zuvor auf der offiziellen Website des Registers ihre Domain verifizieren. Wählen Sie bei der Anforderung dieses Tokens \"INWX\" als Registrar im Dropdown-Menü aus. Sie können den Token hier erhalten: https://register.bank/get-started/

Ich verstehe, dass .bank-Domains spezielle technische Anforderungen haben, um ordnungsgemäß zu funktionieren, einschließlich: Sie müssen DNSSEC verwenden, die DNS-Server müssen von der eigenen Domain oder einer anderen .BANK-Domain stammen, sie funktionieren nur mit SSL (HSTS), ich muss sichere E-Mail-Protokolle wie DMARC und SPF verwenden, und mein Konto muss jederzeit über eine Zwei-Faktor-Authentifizierung (2FA) verfügen.';
$_ADDONLANG['inwx_INSURANCE-ACCEPT-REQUIREMENTS'] = 'Um eine .insurance-Domain zu registrieren, müssen Sie zuvor auf der offiziellen Website des Registers ihre Domain verifizieren. Wählen Sie bei der Anforderung dieses Tokens \"INWX\" als Registrar im Dropdown-Menü aus. Sie können den Token hier erhalten: https://www.register.insurance/get-started/

Ich verstehe, dass .insurance-Domains spezielle technische Anforderungen haben, um ordnungsgemäß zu funktionieren, einschließlich: Sie müssen DNSSEC verwenden, die DNS-Server müssen von der eigenen Domain oder einer anderen .INSURANCE-Domain stammen, sie funktionieren nur mit SSL (HSTS), ich muss sichere E-Mail-Protokolle wie DMARC und SPF verwenden, und mein Konto muss jederzeit über eine Zwei-Faktor-Authentifizierung (2FA) verfügen.';
$_ADDONLANG['inwx_CA-ACCEPT-REGISTRANT-AGREEMENT'] = 'Der Domaininhaber hat das <a href=\"https://www.cira.ca/en/resources/documents/about/registrant-agreement/\" target=\"_blank\">CIRA Registrant Agreement</a> gelesen und akzeptiert diese Registrierungsbedingungen. Das Bestätigen hier im Bestellprozess ist optional - der Domaininhaber erhält alternativ eine E-Mail, in der aufgefordert wird dem Registrant Agreement zuzustimmen.';
$_ADDONLANG['inwx_DK-ACCEPT-TAC'] = '<b>Ja, ich akzeptiere die Nutzungsvereinbarung mit Punktum dk A/S:</b><br/>
.dk-Domainname-Bedingungen
<br/><br/>
Um eine .dk-Domain zu registrieren, müssen Sie eine Vereinbarung mit Punktum dk A/S eingehen. Punktum dk A/S ist der Administrator für alle .dk-Domainnamen.
<br/><br/>
Domainadministrator:<br/>
Punktum dk A/S<br/>
Ørestads Boulevard 108, 11.<br/>
DK-2300 KBH S
<br/><br/>
Hiermit erkläre ich mich einverstanden, eine Vereinbarung über das Nutzungsrecht der angegebenen .dk-Domain gemäß den geltenden Bedingungen einzugehen. Unter anderem bedeutet dies, dass ich sicherstelle, dass meine Kontaktdaten als Registrant jederzeit korrekt sind. Ich werde die Identitätsüberprüfung von Punktum dk A/S durchführen, wenn dies verlangt wird.
<br/><br/>
Mein Recht zur Nutzung der angegebenen .dk-Domain kann unter den in den Nutzungsbedingungen von Punktum dk A/S festgelegten Bedingungen übertragen, ausgesetzt, gelöscht oder blockiert werden.
<br/><br/>
Gemäß Abschnitt 18 (2) (13) des dänischen Verbrauchervertragsgesetzes erkläre ich mich einverstanden, auf das Recht zum Rücktritt von der Vereinbarung über das Nutzungsrecht der angegebenen .dk-Domain zu verzichten.
<br/><br/>
Ich gebe mein Einverständnis, dass Punktum dk A/S als Domainadministrator meine personenbezogenen Daten gemäß seiner Datenschutzrichtlinie verwendet.
<br/><br/>
Ich erkläre mich bereit, die Gebühr für die erste Registrierungsperiode der angegebenen .dk-Domain an den von mir ausgewählten Registrar zu zahlen.
<br/><br/>
Links:
<br/><br/>
<a href=\"https://www.punktum.dk/en/articles/terms-and-conditions-for-the-right-of-use-to-a-dk-domain-name\" target=\"_blank\">Nutzungsbedingungen für das Recht zur Nutzung einer .dk-Domain</a><br/>
<a href=\"https://www.punktum.dk/en/articles/privacy-policy\" target=\"_blank\">Datenschutzrichtlinie</a>';
$_ADDONLANG['inwx_ACKNOWLEDGE-SECURE-ONLY-CHANNEL'] = 'Mir ist bekannt, dass meine neue .CHANNEL-Domain durch die Voraktivierung von HSTS besonders sicher ist und ich meine Webseite mit einem SSL Zertifikat betreiben muss um diese Domain verwenden zu können. Ich wurde von INWX informiert, wie ich ein SSL Zertifikat bestellen kann, um meine .CHANNEL-Domain zu nutzen.';
$_ADDONLANG['inwx_CHANNEL-ACCEPT-REQUIREMENTS'] = '.channel ist ausschließlich für Content-Ersteller und -Publisher zur Monetarisierung ihrer Inhalte gedacht. Alle .channel-Domains müssen dem Benutzer eine Website bieten, auf der der Ersteller seinen Inhalt oder sein Publikum monetarisieren kann. Andere Anwendungsfälle sind nicht zulässig. Durch die Registrierung einer .channel-Domain erklären Sie sich damit einverstanden, die .channel-Registrierungsrichtlinie zu befolgen. Die vollständigen Richtlinien finden Sie unter g.co/registry/channelRegistration.';
$_ADDONLANG['inwx_ES-ID'] = 'Registrant ID (NIF/NIE/VAT/ID/Passport)';
$_ADDONLANG['inwx_ES-ADMIN-ID'] = 'Admin ID (NIF/NIE/ID/Passport)';
$_ADDONLANG['inwx_ES-TECH-ID'] = 'Tech ID (NIF/NIE/ID/Passport)';
$_ADDONLANG['inwx_ES-BILLING-ID'] = 'Billing ID (NIF/NIE/ID/Passport)';
$_ADDONLANG['inwx_es_contacts'] = '<strong>WICHTIGE INFORMATION</strong>
<ul>
<li><strong>INHABER</strong>: Der INHABER-Kontakt kann eine natürliche Person oder ein Unternehmen/eine Organisation sein.</li>
<li><strong>ADMINISTRATIVER KONTAKT</strong>: Der ADMINISTRATIVE kontakt MUSS eine natürliche Person sein, ein Unternehmen ist nicht zulässig.</li>
</ul>';
