name: Release

on:
  push:
    branches:
      - master # or main

jobs:
  get-next-version:
    uses: semantic-release-action/next-release-version/.github/workflows/next-release-version.yml@v4

  build:
    runs-on: ubuntu-latest
    if: needs.get-next-version.outputs.new-release-published == 'true'
    needs:
      - get-next-version
    steps:
      # Setup container
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9
      - name: Setup Node LTS
        uses: actions/setup-node@v4
        with:
          cache: 'pnpm'
          node-version: "lts/*"
      - uses: php-actions/composer@v6
      - id: commit
        uses: prompt/actions-commit-hash@v3

      # Run release
      - run: pnpm install
      - run: pnpm lint-staged
      - name: Replace hardcoded version number
        run: git ls-files '*.php' | xargs sed -i 's/0.0.0-semantic-release/${{ needs.get-next-version.outputs.new-release-version }}+${{ steps.commit.outputs.short }}/g'
      - name: Create release.zip
        uses: montudor/action-zip@v1
        with:
          args: zip -qq -r release.zip modules LICENSE README.md
      - name: Generate checksum
        uses: jmgilman/actions-generate-checksum@v1
        with:
          patterns: |
            release.zip
      - name: Release
        env:
          WHMCSMP_LOGIN: ${{ vars.WHMCSMP_LOGIN }}
          WHMCSMP_PASSWORD: ${{ secrets.WHMCSMP_PASSWORD }}
          WHMCSMP_PRODUCTID: ${{ vars.WHMCSMP_PRODUCTID }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: pnpm semantic-release
