name: Release

on:
  push:
    branches:
      - master # or main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9
      - name: Setup Node LTS
        uses: actions/setup-node@v4
        cache: 'pnpm'
        with:
          node-version: "lts/*"
      - name: Install dependencies
        run: pnpm install
      - name: Release
        env:
          WHMCSMP_LOGIN: ${{ variables.WHMCSMP_LOGIN }}
          WHMCSMP_PASSWORD: ${{ secrets.WHMCSMP_PASSWORD }}
          WHMCSMP_PRODUCTID: ${{ variables.WHMCSMP_PRODUCTID }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: pnpm semantic-release
      - name: Generate checksum
        uses: jmgilman/actions-generate-checksum@v1
        with:
          patterns: |
            release.zip
