name: Release

on:
  push:
    branches:
      - master # or main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Setup container
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9
      - name: Setup Node LTS
        uses: actions/setup-node@v4
        with:
          cache: 'pnpm'
          node-version: "lts/*"
      - uses: php-actions/composer@v6

      # Run release
      - run: pnpm install
      - run: pnpm lint-staged
      - name: Create release.zip
        uses: montudor/action-zip@v1
        with:
          args: zip -qq -r release.zip modules LICENSE README.md
      - name: Generate checksum
        uses: jmgilman/actions-generate-checksum@v1
        with:
          patterns: |
            release.zip
      - name: Release
        env:
          WHMCSMP_LOGIN: ${{ vars.WHMCSMP_LOGIN }}
          WHMCSMP_PASSWORD: ${{ secrets.WHMCSMP_PASSWORD }}
          WHMCSMP_PRODUCTID: ${{ vars.WHMCSMP_PRODUCTID }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: pnpm semantic-release
